### PR TITLE
Merge HAFS.v1.0.0 back to develop

### LINKED ISSUE #179: Capability to skip vortex initialization for very weak storms
## Description
Add the capability to skip vortex initialization for very weak storms.
## Proposed solution
Add a workflow config option to skip the vortex initialization procedure for weak storms/cycles.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #182: Prepare HAFS version files needed for HAFSv1 operational implementation
## Description
Prepare HAFS version files needed for HAFSv1 operational implementation

## Proposed solution
Prepare the needed build.ver and run.ver according to HWRF/HMON and GFS examples.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #183: HAFS application workflow cleanup and optimization for HAFSv1 operational implementation
## Description
Clean up and optimize the HAFS application workflow for HAFSv1 and make it be compliant with operational implementation standards.

## Proposed solution
Submodule and source code cleanup/re-organization, jobs/scripts/ush/parm/rocoto scripting/configuring system cleanup/optimization, etc.

## Status (optional)
Working in progress, happening in the production/hafs.v1 branch.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #187: Enable HAFSv1 Ecflow workflow capability
## Description
Develop and add the Ecflow support for the HAFSv1, needed for HAFSv1 operational transition.

## Proposed solution
Based on the HAFS Rocoto workflow and operational HWRF/HMON Ecflow workflow, @lgannoaa from EIB is working together with EMC hurricane project team on developing and testing HAFSv1 Ecflow workflow.

## Related to (optional)
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #190: Merge HAFSv1 production branch back to develop branch
## Description
HAFSv1 code package has been delivered to NCO for operational transition. It would be beneficial to merge the HAFSv1 developments/configurations back the HAFS develop branch.

## Proposed solution
A feature/hafsv1_merge branched off from the production/hafs.v1 branch will be used to merge all HAFSv1 developments back to HAFS develop branch.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #191: Improve and optimize HAFS workflow level regression tests
## Description
As we now finalized and delivered HAFSv1 code package, it would be beneficial to improve and optimize the HAFS workflow level regression tests.

## Proposed solution
Discuss, drop off, optimize, or add new HAFS workflow level regression tests.

## Status (optional)
Discussion/working sessions among DTC and EMC collaborators were conducted to re-enable the HAFS application/workflow level regression tests in the feature/hafsv1_merge branch, which will be merged back to HAFS develop branch through PR #193.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/193

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
HAFSv1 code package has been delivered to NCO for operational transition. This PR is to merge the HAFS.v1.0.0 configurations (including HFSA and HFSB) back to HAFS develop branch.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/191
- fixes hafs-community/HAFS/issues/190
- fixes hafs-community/HAFS/issues/187
- fixes hafs-community/HAFS/issues/183
- fixes hafs-community/HAFS/issues/182
- fixes hafs-community/HAFS/issues/179

## Contributors (optional)
The HAFSv1 was collaboratively developed, tested, and transitioned to operations by the UFS Hurricane Application Team.

## Tests conducted
HAFSv1 final retrospective tests for both HFSA and HFSB configurations were conducted on multiple HAFS supported platforms.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS2

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
I think we are ready to kick off the regression tests on the four HAFS supported platforms.
Wondering if DTC (@KathrynNewman, @mrinalbiswas, @SamuelTrahanNOAA) can help to take care of the RTs on Orion and Hera. @LinZhu-NOAA, could you please take care of the RT on WCOSS2? And @BijuThomas-NOAA, please help to test on Jet. Thanks!

P.S., here are the steps to clone, install, and run the HAFS RTs:
```
git clone -b feature/hafsv1_merge --recursive https://github.com/hafs-community/HAFS.git ./
cd sorc
./install_hafs.sh > install_hafs.log 2>&1
cd ../rocoto
export HOMEhafs=$(dirname $(pwd))
./cronjob_hafs_rt.sh # repeatedly running or in crontab
```

**Comment by BinLiu-NOAA** [comment]
Since there will be a HAFS community support related telecom discussion tomorrow (Tuesday, 07/11/2023) afternoon, if possible, we would try to get this PR merged by tomorrow noon. Thanks!

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA The regression tests completed successfully on WCOSS2.

**Review by LinZhu-NOAA — APPROVED** [review]

**Review by panll — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks, @LinZhu-NOAA! Glad that the application level regression tests went through on WCOSS2 successfully.
@BijuThomas-NOAA, for Jet, looks like it is under maintenance today, so we will skip the RTs on Jet.
@SamuelTrahanNOAA, @mrinalbiswas, @KathrynNewman, not sure if you have kicked off the RTs on Orion or Hera.
I did a try on Orion from my end, and all the 8 HAFS application/workflow level RTs completed successfully.

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA I am kicked off RTs on Orion and Hera. I am expecting Orion RT to finish this afternoon. Hera RTs will probably finish by evening, if everything goes fine.

**Comment by BinLiu-NOAA** [comment]
@mrinalbiswas, thanks for the update! Much appreciated!

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA: 6 HAFS application/workflow level RTs completed successfully on Jet before the maintenance. A _module purge_ is needed in the analysis job script.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA: 6 HAFS application/workflow level RTs completed successfully on Jet before the maintenance. A _module purge_ is needed in the analysis job script.

Thanks, @BijuThomas-NOAA! Could you please help commit the "module purge" related changes (most likely needed on Jet, Hera and Orion) back to this feature branch? Note: My RTs on Orion went through successfully without this module purge change though.

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA RTs passed on Orion

**Comment by BinLiu-NOAA** [comment]
Thanks, @mrinalbiswas!

**Comment by BinLiu-NOAA** [comment]
@mrinalbiswas, could you please git pull to get the latest jobs/JHAFS_ANALYSIS changes, which should let the analysis job go through on Hera? Thanks!

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA Couple of the RTs (hafsv1_merge_rt_hfsb_dev and hafsv1_merge_rt_hfsa_dev_ww3) failed on Hera. The log file says: 
-101 NetCDF: HDF error
 ././ensemble_data/enkfgdas.2020082500.atmf003_ens_032

I think the file size (path copied below) is smaller than the other ones. Can you please check it?

/scratch1/NCEPDEV/hwrf/noscrub/hafs-input/COMGFSv16/enkfgdas.20200825/00/atmos/mem032/gdas.t00z.atmf003.nc

**Comment by BijuThomas-NOAA** [comment]
RTs on Jet completed  successfully

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA Couple of the RTs (hafsv1_merge_rt_hfsb_dev and hafsv1_merge_rt_hfsa_dev_ww3) failed on Hera. The log file says: -101 NetCDF: HDF error ././ensemble_data/enkfgdas.2020082500.atmf003_ens_032
> 
> I think the file size (path copied below) is smaller than the other ones. Can you please check it?
> 
> /scratch1/NCEPDEV/hwrf/noscrub/hafs-input/COMGFSv16/enkfgdas.20200825/00/atmos/mem032/gdas.t00z.atmf003.nc

@mrinalbiswas, I am currently rsyncing those incomplete/missing enkfgdas input files from Jet to Hera, it will take a while, but I will let you know once it's done. Then you can rewind the failed analysis jobs. Thanks!

**Comment by BinLiu-NOAA** [comment]
@mrinalbiswas, please rewind the failed analysis jobs for your HAFS RTs on Hera. It should be able to go through now. The needed enkfgdas files are rsynced from Jet to Hera. Thanks!

**Comment by SamuelTrahanNOAA** [comment]
On Orion, the run_hafs.py keeps freezing during "import xarray as xr". Eventually it passes that point, but that can take over a minute.

**Comment by SamuelTrahanNOAA** [comment]
Also, the run_hafs.py tries to call mpiexec, mpirun, aprun, etc. when detecting the MPI implementation. The Hera process scanner sometimes flags that and kills the run_hafs.py. I have a fix for that, which will use "produtil.mpi_impl.no_mpi". It probably belongs in a separate PR, though.

**Comment by SamuelTrahanNOAA** [comment]
A third issue is that the archiving is enabled by default in the system.conf. That means the regression tests will archive results to 5 year archives unless the user turns it off. You already disable scrubbing, so people will have output to look at if it's wrong. Archiving serves no purpose.

I suggest you explicitly turn off archiving (config.archive=none) in the regression test script.

**Comment by BinLiu-NOAA** [comment]
> On Orion, the run_hafs.py keeps freezing during "import xarray as xr". Eventually it passes that point, but that can take over a minute.

@SamuelTrahanNOAA, Thanks for this note! This could either be related to the Python environment (@MariaAristizabal-NOAA FYI) we use on Orion or sometimes the Orion disk/filesystem slowdown. I recalled encountering this from my end as well. We can pay more attention ton in the future.

**Comment by BinLiu-NOAA** [comment]
> Also, the run_hafs.py tries to call mpiexec, mpirun, aprun, etc. when detecting the MPI implementation. The Hera process scanner sometimes flags that and kills the run_hafs.py. I have a fix for that, which will use "produtil.mpi_impl.no_mpi". It probably belongs in a separate PR, though.

@SamuelTrahanNOAA, appreciated it if you can help to create an issue for this and later on create a PR to fix this. Thanks!

**Comment by BinLiu-NOAA** [comment]
> I suggest you explicitly turn off archiving (config.archive=none) in the regression test script.

Thanks for the good suggestion, @SamuelTrahanNOAA! I will update cronjob_hafs_rt.sh accordingly.

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA RTs passed on Hera.

**Review by KathrynNewman — APPROVED** [review]

**Pull request merged**
