### PR TITLE
Sync HAFS submodules with their corresponding authoritative branches

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes  
Sync HAFS submodules with their corresponding authoritative branches:

- hafs_forecast.fd as of 08/05/2021
- hafs_gsi.fd as of 08/06/2021 plus the dual-resolution 3DEnVar bug fix
- hafs_post.fd as of 08/02/2021
- hafs_utils.fd as of  as of 07/23/2021
- hafs_graphics.fd/hrd_gplot as of 08/10/2021
- hafs_graphics.fd/emc_graphics as of 08/10/2021

Besides application level changes were made accordingly with the updated submodules.

## Issues addressed

This PR addresses issue #80.

Notes:
- The [bug of wrong Time dimension in FV3 restart sfc_data files](https://github.com/NOAA-EMC/fv3atm/issues/344) has been fixed in ufs-weather-model through this ufs-weather-model [PR](https://github.com/ufs-community/ufs-weather-model/pull/702). 
- The bug fix in for the dual-resolution EnVar analysis in GSI (hafs_gsi.fd) contributed from OU collaborators has also been included in this PR. With that the HAFS ENSDA configurations can now work properly.
- As for the hafs_forecast.fd submodule, support/HAFS branch is identical to the ufs-weather-model develop branch as of 08/05/2021. More information can be found through this PR (https://github.com/ufs-community/ufs-weather-model/pull/715)

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

HAFS application level regression tests went through on Orion. The two-cycle HAFS ENSDA test also ran through on Orion.

## Application-level regression test status  
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS Dell P3
- [x] WCOSS Cray

Again, appreciate it if you could help to run the regression tests as you helped previously!
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (Jet, we probably will skip Jet since it is occupied by the HFIP real-time parallel experiments under reservation)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@ghassan-alaka and @AndrewHazelton, I have synced to point to the latest support/HAFS branch of GPLOT. Let me know if there are any hrdgraphics related changes you want to add to this PR at the application/workflow level.

**Comment by ghassan-alaka** [comment]
@BinLiu-NOAA, yes there are a few changes that I would like to make in the HAFS scripts/ and jobs/ directories for hrdgraphics. All changes are in my HAFS branch (_HAFS/hotfix-hrdgraphics_). How would you like to merge those changes into the HAFS/develop branch? The most logical step seems like we should merge the _hotfix-hrdgraphics_ branch into _feature/hafs_sync_202107_ and have it be a part of this current PR. What do you think?

Also, I noticed that you've updated hafs_graphics.fd/hrd_gplot as of 07/27/2021. I just merged another series of updates that would probably be useful for anyone running the hrdgraphics task. Could you make sure these latest changes get into this PR? Here is a link to the _GPLOT/support/HAFS_ PR:  https://github.com/hafs-community/GPLOT/pull/8.

**Comment by BinLiu-NOAA** [comment]
Thanks, @ghassan-alaka! Yes, I have just synced this feature/hafs_sync_202107 branch with your hotfix-hrdgraphics branch, so that the application/workflow level get the related hrdgraphics needed changes. In the meantime, I also updated the hafs_graphics.fd/hrd_gplot submodule to point the latest commit of the support/HAFS branch as of today (08/10/2021). I have added you as a reviewer for this PR. Please help to check this PR now has all the hrd graphics related changes you want to go back HAFS develop branch. Thanks!

**Comment by panll** [comment]
The regression tests on Orion passed. @BinLiu-NOAA @evankalina However, the compiling of hycom_utils failed on Hera, here are the error messages: /scratch2/BMC/fv3lam/lpan/test/08102021/hafs_sync_202107/sorc/logs/build_hycom_utils.log.

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA, The RT tests with feature/hafs_sync_202107 branch is successful on WCOSS(Cray)

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA The regression tests completed successfully on WCOSS-Dell.

**Review by LinZhu-NOAA — DISMISSED** [review]

**Review by BijuThomas-NOAA — DISMISSED** [review]

**Review by panll — DISMISSED** [review]

**Comment by panll** [comment]
Regression tests completed successfully on Hera. @BinLiu-NOAA @evankalina

**Review by evankalina — DISMISSED** [review]

**Review by ghassan-alaka — APPROVED** [review]
Everything looks good for the two _hrdgraphics_ files that were modified.

**Comment by BinLiu-NOAA** [comment]
Thanks for conducting the regression tests and fix the issues! I think this PR is ready to merge. Need at another review approval though. Thanks!

**Review by evankalina — APPROVED** [review]

**Pull request merged**
