### PR TITLE
Feature/add fms2 io nml fieldtable

### LINKED ISSUE #112: Sync to use the same field_table as in ufs-weather-model HAFS regression tests
## Description
Sync to use the same field_table as in ufs-weather-model HAFS regression tests:
sorc/hafs_forecast.fd/tests/parm/field_table/field_table_hafs

## Proposed solution
Copy or link sorc/hafs_forecast.fd/tests/parm/field_table/field_table_hafs into the corresponding parm/forecast/[regional|globnest]/field_table files.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
- addressed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #117: Add the fms2_io_nml namelist section with netcdf_default_format of netcdf4 in input*.nml
## Description
Add the fms2_io_nml namelist section with netcdf_default_format of netcdf4 in input*.nml 
&fms2_io_nml
netcdf_default_format="netcdf4"
/
Otherwise, the default was the NetCDF "64-bit offset" version, which has issues to support large files.

Note: This information is from the RRFS application team (Eric Rogers) with the suggestion from @bensonr.

## Proposed solution
Add the above-mentioned namelist section in the input*.nml files for the forecast job (ufs-weather-model).

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- addressed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by mrinalbiswas**
## Description of changes
Copied the field_table_hafs to regional and globnest to sync the same field_table as in ufs-weather-model HAFS RTs.
Not copying the field_table from the RT into the *_hwrf directories, because those field_tables are specific to the HWRF physics suite in HAFS, and that suite has a unique set of tracers.
Fixes Issue #112

Added the fms2_io_nml namelist section with netcdf_default_format of netcdf4 in input*.nml
Otherwise, the default was the NetCDF "64-bit offset" version, which has issues to support large files.
Fixes Issue #117

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/112
- fixes hafs-community/HAFS/issues/117

## Contributors (optional)
@BinLiu-NOAA 
@bensonr

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS Dell P3
- [x] WCOSS Cray

### CODE REVIEW

**Comment by panll** [comment]
Regression tests passed on Hera. One minor issue is that the module "esmf/8_1_0_beta_snapshot_27" in hafs_utils.fd/modulefiles/build.hera.intel does not exist and needs to be changed to one of the exist esmf modules (e.g. module load esmf/8_2_0_beta_snapshot_14).
@mrinalbiswas @BinLiu-NOAA @evankalina

**Comment by BinLiu-NOAA** [comment]
Thanks, @panll! I have updated the support/HAFS branch of UFS_UTILS to load emsf/8_2_0 on Hera instead.

@mrinalbiswas, could you please update your PR branch to point to the latest support/HAFS branch for hafs_utils.fd?
https://github.com/hafs-community/UFS_UTILS/commits/support/HAFS

Thanks!

**Comment by BinLiu-NOAA** [comment]
Since @panll has finished the RTs on Hera, could @mrinalbiswas please help to conduct the RTs on Orion (if you have not yet done so), @JunghoonShin-NOAA help to run RTs on Jet, @BijuThomas-NOAA on wcoss_cray, and @ChunxiZhang-NOAA on wcoss_dell_p3 (@LinZhu-NOAA is on leave this week)?

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
Do you know the exact name of this branch? I used the following commands to pull the code, but it didn't work.

git clone -b feature/add_fms2_io_nml_fieldtable --recursive https://github.com/hafs-community/HAFS.git ./

Thank you.

**Comment by BijuThomas-NOAA** [comment]
> 
@JunghoonShin-NOAA 
I think it's the  branch in this fork: https://github.com/mrinalbiswas/HAFS.git

**Comment by JunghoonShin-NOAA** [comment]
Thanks Biju! I can download the code now.

**Comment by BijuThomas-NOAA** [comment]
> 

@BinLiu-NOAA 
Regressions tests with the branch feature/add_fms2_io_nml_fieldtable were successful on WCOSS-CRAY

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin, Regression test on Jet completed successfully.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Comment by mrinalbiswas** [comment]
RTs passed on Orion. I will update the PR branch as @BinLiu-NOAA suggested.

**Comment by ChunxiZhang-NOAA** [comment]
Regression test on wcoss_dell_p3 were successful.

**Review by panll — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks to All! All regression tests have passed, ready to merge.

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good to me.

**Review by evankalina — APPROVED** [review]

**Pull request merged**
