### PR TITLE
Merge feature/hafs_ensda branch back to develop

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
Features and enhancements with this PR:
- The following HAFS DA workflow capabilities for the single regional domain configuration with a regular gnomonic grid or Extended Schmidt Gnomonic (ESG) grid are available now, including:
  - Cold-start, warm-start capabilities
  - GSI-based Vortex Relocation (originally developed by Henry Winterbottom, not fully tested though)
  - 3DVar and 3DEnVar with GDAS ensembles
  - FGAT capability (OU)
  - 3DEnVar with dual-resolution self-cycled EnKF ensembles (EMC/OU)
  - Assimilating all observations ingested in HWRF/GDAS/GFS (tempdrop drifting not considered yet)
- Generalized HAFS workflow task/job names according to [the latest HAFS workflow schematic](https://lucid.app/lucidchart/c14f0775-588c-46e8-8553-ca38e6c8c417/view?page=AJqodY-E682U#) as of 04/16/2021, together with substantial cleanup and optimization for the workflow scripts.
- HAFS submodules (hafs_forecast.fd, hafs_utils.fd, hafs_post.fd, and hafs_gsi.fd) were synced with their latest authoritative branches as of 04/16/2021. For the hafs_forecast.fd submodule (the support/HAFS branch of ufs-weather-model), it also picked up the following two upcoming PRs (which have not yet gone into its develop branch).
  - Add 'netcdf' and 'grib2' to input 'source' options in regional IC/LBC routines [PR](https://github.com/ufs-community/ufs-weather-model/pull/526)
  - Add new PBL diagnostic variables dkt and dku [PR](https://github.com/ufs-community/ufs-weather-model/pull/505)
- Clean up hafs_tools.fd and use CMake to build HAFS specific components including hafs_tools.fd, hafs_vortextracker.fd, and hafs_hycom_utils.fd. (Biju)
- Use hpc-stack version libraries when applicable. (Biju)
- Switch to use GFSv16 version of scale-aware TKE EDMF PBL scheme as the default PBL scheme. (Chunxi, Weiguo, JungHoon)

Notes: 
- HAFS DA workflow capabilities are mainly developed by the HAFS DA Development Team including: EMC hurricane project team in close collaboration with the FV3CAM group; OU collaborators; UMD collaborators; HRD and UM CIMAS collaborators; DTC collaborators; University at Albany collaborators, etc.
- This version of feature/hafs_ensda branch will be used in the HAFSv0.2a phase-2 combined (H2PC) experiment, as well as the HAFSv0.2a DA baseline and control experiments (H2DB and H2DC).

### CODE REVIEW

**Comment by AndrewHazelton** [comment]
Does this PR include the bug fix for the global-nested version with CCPP where the deep+shallow and shallow-only convection produce the same results?

**Comment by BinLiu-NOAA** [comment]
Again, appreciate it if you could help to run the regression tests as you helped previously!
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (xjet)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)
@ChunxiZhang-NOAA (ufs-weather-model level regression tests)

- To conduct the HAFS application level regression tests, you can:
A. Clone and checkout the branch, e.g.,
git clone -b feature/hafs_ensda --recursive https://github.com/hafs-community/HAFS.git ./hafs_ensda
B. Build and install HAFS
cd hafs_ensda/sorc
./install_hafs.sh # Afterward, please check or edit the ../parm/system.conf if needed.
C. Edit and run the cronjob driver as a cron job
cd ../rocoto
vi cronjob_hafs_rt.sh # make sure to use the correct platform and directory
./cronjob_hafs_rt.sh
A rocoto_utils.sh script is now available under the rocoto dir, which can be used to easily check status for rocoto tasks and/or rewind failed rocoto tasks.
Usage:
  ./rocoto_utils.sh [-a | -f | -r | -s] # Loop over all *.xml files
  ./rocoto_utils.sh [-a | -f | -r | -s] hafs # Loop over all *.xml files starting with hafs
  -a: check all active (SUBMITTING|QUEUED|RUNNING|DEAD|UNKNOWN|FAILED) tasks
  -f: check all failed (DEAD|UNKNOWN|FAILED) tasks
  -r: check and rewind all failed (DEAD|UNKNOWN|FAILED) tasks
  -s: check status for all tasks

- To run the ufs-weather-model level regression tests:
cd sorc/hafs_forecast.fd/tests
vi detect_machine.sh and update this line into export ACCNR=${ACCNR:-hurricane} or your own compute project name.
Launch the ufs-weather-model level regression tests
nohup ./rt.sh -e > rt.log 2>&1 &

Notes:
- DA regression tests are not added yet, which can be done in the future.
- ufs-weather-model level regression tests should run through, but may or may not produce identical results to the baseline, since there are two additional features cherry-picked from upcoming PRs.
- There is a pending issue for wcoss_cray esmf module, which hopefully will be fixed from the hpc-stack side soon. So, please hold the wcoss_cray regression tests for now.

**Comment by BinLiu-NOAA** [comment]
> Does this PR include the bug fix for the global-nested version with CCPP where the deep+shallow and shallow-only convection produce the same results?

@AndrewHazelton, Yes it should be. So please help to test it out. Thanks!

**Review by AndrewHazelton — DISMISSED** [review]
Looks like quite a few changes - look forward to testing it soon.

**Comment by LinZhu-NOAA** [comment]
The regression tests completed successfully on WCOSS DELL with the changes made by Bin and Biju for atmos_ic, ocn_prep, ocn_post scripts and g2 lib for tracker.

**Review by LinZhu-NOAA — DISMISSED** [review]

**Review by BijuThomas-NOAA — DISMISSED** [review]
The regression tests completed successfully on WCOSS-CRAY

**Comment by BinLiu-NOAA** [comment]
The upgrade from the esmf/810bs27 to esmf/810bs47 caused an issue to substantially slow down the forecast model when using omp threading (by resetting thread to 1 in the forecast model). More details can be seen in [this issue](https://github.com/NOAA-EMC/hpc-stack/issues/208). A newer version of esmf/811bs03 has been tested and fixed the issue. So, we need to wait the new esmf/811bs03 besing installed and switch to use it in HAFS. Otherwise, the HAFS forecast job has been substantially slowed down and will run out of wallclock limit in most cases.

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
I confirmed that all regression tests on xJet completed successfully.
Thank you.

**Comment by mrinalbiswas** [comment]
RT on Orion passed (codes checked out on 4/20). There were several commits made after the test started. Building and testing it again.

**Comment by evankalina** [comment]
RT has passed on Hera; no changes needed. This test did not include @BinLiu-NOAA's two most recent commits (clean up jobs/JHAFS_PRODUCT; update .gitmodules to point support/HAFS branch for hafs_gsi.fd), but included all of the others. Should I repeat the RTs?

**Comment by BinLiu-NOAA** [comment]
> RT has passed on Hera; no changes needed. This test did not include @BinLiu-NOAA's two most recent commits (clean up jobs/JHAFS_PRODUCT; update .gitmodules to point support/HAFS branch for hafs_gsi.fd), but included all of the others. Should I repeat the RTs?

Thanks @evankalina! And for the last two commits, you do not need to test them again. They do not change results. I am also trying to wait for the esmf/811 being installed under hpc-stack. Again, that will not change results either. Once that's updated, we can merge this PR into the develop branch.

**Comment by ChunxiZhang-NOAA** [comment]
I cloned the feature/hafs_ensda branch this afternoon and did a ufs-model-level regression test. All cpld failed for results check. I believed all latest commits are included in this copy.

**Comment by BinLiu-NOAA** [comment]
> I cloned the feature/hafs_ensda branch this afternoon and did a ufs-model-level regression test. All cpld failed for results check. I believed all latest commits are included in this copy.

Thanks @ChunxiZhang-NOAA! As you can see from the PR description, it actually has some changes ahead of the ufs-weather-model develop branch. So, as long as the regression tests can successfully run through, we do not expect all the regression tests produce identical results. Next time after we syncing with the ufs-weather-model develop, we should then expect reproducing every regression tests.

**Comment by ChunxiZhang-NOAA** [comment]
@BinLiu-NOAA  I see, thanks.

**Comment by BinLiu-NOAA** [comment]
Now esmf/8_1_1 is available on all HAFS supported platforms. I think we are ready to merge this PR. Waiting for at least two review approvals. Thanks!

**Review by evankalina — APPROVED** [review]
I am good with this being merged. RTs have passed on Hera and Orion (among other platforms). It is very exciting to have all of these new DA capabilities in HAFS.

**Review by AndrewHazelton — APPROVED** [review]
Looks good!

**Pull request merged**
