### PR TITLE
Feature/hafs mom6 3dvar

### PR DESCRIPTION
**Pull request by YongzuoLi-NOAA**
Archive and share MOM6 3DVAR related program files.

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@YongzuoLi-NOAA, currently since this series of developments are still working in progress. It makes more sense to me to keep these features/capabilities in this feature/hafs_mom6_3dvar branch at this moment. We probably can consider merging/bring these changes back to HAFS develop branch once the capabilities are mature in the future. Thanks!

**Comment by YongzuoLi-NOAA** [comment]
@BinLiu-NOAA Yes, now this branch is for me to archive codes.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA Yes, now this branch is for me to archive codes.

@YongzuoLi-NOAA, ok, sounds good to me. With that, I will go ahead to close this PR at this moment. You can keep updating and committing your developments to this feature/hafs_mom6_3dvar branch. In the future, once the capability is mature and ready to go back to HAFS develop, we can then create pull request to merge it back to HAFS develop. Thanks!

**Comment by YongzuoLi-NOAA** [comment]
@BinLiu-NOAA Thank you.

**Pull request closed without merging**
