### PR TITLE
Enable using different write grid component settings in atm_init and add/unify compute resources in rocoto site entity files

### LINKED ISSUE #207: Enable atm_init using different write grid component settings and compute resource cleanup in rocoto site entity files
## Description

- Enable atm_init using different write_groups and write_tasks_per_group settings from the forecast job. This can save computation resources for the atm_init jobs, meanwhile let the forecast job more flexible to choose other write grid component settings.
- Add, cleanup, and unify compute resources in rocoto site entity files.

## Proposed solution

- Add atm_init specific configure options: write_groups_init and write_tasks_per_group_init.
- Update rocoto site entity files.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/209

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
Provide a description of what this PR does. What bug does it fix, or what feature does it add? Do you expect that this PR will change answers, and if so, under what circumstances? If this PR is for a physics innovation, please provide references to any relevant scientific papers.

- Enable atm_init using different write_groups and write_tasks_per_group settings from the forecast job. 
- Add, cleanup, and unify compute resources in rocoto site entity files.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/207

## Dependencies (optional)
If submodule PRs are required, please link them below. For example:
- wait for hafs-community/HAFS/pull/206

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

Tests on WCOSS2 were conducted.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet: Partially completed. Will skip Jet for this PR, since Jet is currently reserved for HFIP real-time parallel experiments.
- [x] Hera
- [x] Orion
- [x] WCOSS2

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@BijuThomas-NOAA could you please help to run HAFS RTs for this PR on WCOSS2?
@KathrynNewman and @ulmononian, please help coordinate and ask DTC and EPIC team members to run HAFS RTs on Jet, Hera and Orion. Much appreicated!

**Comment by ulmononian** [comment]
@BinLiu-NOAA i will run this on jet, orion, and hera for the sake of building more experience with the workflow, but @KathrynNewman please feel free to also run on any or all of these machines as well to verify.

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA @ulmononian @KathrynNewman  I will run the RTs on Orion and Hera. I can run on Jet too, if needed. Just let me know.

**Comment by KathrynNewman** [comment]
@ulmononian, sounds good! Let us know if you encounter any issues. @mrinalbiswas will run on Hera and Orion (and Jet if needed) this time as a sanity check, but we can probably hand-off RTs completely soon if this goes well on all platforms. Thanks!

**Comment by ulmononian** [comment]
looks like the RTs passed (for the most part) on orion & hera. jet is running much more slowly, so they are not yet completed there. 

on orion, i see that for some of the tests, the `scrub_com`, `scrub_work`, and `completion` tasks either do not run or just hang in a `SUBMITTED` state. this also happens for a few tests on hera. these are the only workflow tasks that are not showing as `SUCCEEDED`. is this expected?

if someone wants to take a look for a sanity check, the directories are:

orion: `/work2/noaa/epic-ps/cbook/HAFS_wrk/save/PR_209/rocoto`
hera: `/scratch1/NCEPDEV/stmp4/Cameron.Book/HAFS_wrk/save/PR_209/rocoto`

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA RTs passed on WCOSS2

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by ulmononian** [comment]
jet RTs are still sitting in the queue due to priority or node availability issues. the forecast tasks are all waiting.

**Comment by ulmononian** [comment]
unfortunately, i am still having issues on jet. so far, it seems that only 3 of the RTs were actually able to start (these are the ones i mentioned in my previous comment that are just hanging in the queue at the forecast step, namely: `regional_static_C192s1n4_atm_ocn_wav`, `regional_static_C192s1n4_atm_3denvar`, & `regional_atm_ocn_wav`). for the remainder of the RTs, if i do `./hafs_rt_status.sh`, i see:

```
[Cameron.Book@fe4 rocoto]$ ./hafs_rt_status.sh
hafs-PR_209_rt_globnest_atm-13L-2020082512
/mnt/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/rocoto
Running PR_209_rt_globnest_atm-13L-2020082512 configuration
08/11/23 13:48:18 UTC :: hafs-PR_209_rt_globnest_atm-13L-2020082512.xml :: Fatal error: Document is empty at hafs-PR_209_rt_globnest_atm-13L-2020082512.xml:1.
08/11/23 13:48:19 UTC :: hafs-PR_209_rt_globnest_atm-13L-2020082512.xml :: Fatal error: Document is empty at hafs-PR_209_rt_globnest_atm-13L-2020082512.xml:1.
/usr/bin/find: '/PR_209_rt_globnest_atm/com/2020082512/13L': No such file or directory
ROCOTO SAYS COMPLETION TASK DID NOT SUCCEED
STORM1.DONE, TRACKER OUTPUT DO NOT EXIST
hafs-PR_209_rt_globnest_static_atm-00L-2020082512
/mnt/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/rocoto
Running PR_209_rt_globnest_static_atm-00L-2020082512 configuration
08/11/23 13:48:20 UTC :: hafs-PR_209_rt_globnest_static_atm-00L-2020082512.xml :: Fatal error: Document is empty at hafs-PR_209_rt_globnest_static_atm-00L-2020082512.xml:1.
08/11/23 13:48:21 UTC :: hafs-PR_209_rt_globnest_static_atm-00L-2020082512.xml :: Fatal error: Document is empty at hafs-PR_209_rt_globnest_static_atm-00L-2020082512.xml:1.
/usr/bin/find: '/PR_209_rt_globnest_static_atm/com/2020082512/00L': No such file or directory
ROCOTO SAYS COMPLETION TASK DID NOT SUCCEED
STORM1.DONE, TRACKER OUTPUT DO NOT EXIST
hafs-PR_209_rt_hfsa_dev_ww3-13L-2020082506
/mnt/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/rocoto
Running PR_209_rt_hfsa_dev_ww3-13L-2020082506 configuration
08/11/23 13:48:21 UTC :: hafs-PR_209_rt_hfsa_dev_ww3-13L-2020082506.xml :: attempt to write a readonly database
08/11/23 13:48:22 UTC :: hafs-PR_209_rt_hfsa_dev_ww3-13L-2020082506.xml :: attempt to write a readonly database
/usr/bin/find: '/PR_209_rt_hfsa_dev_ww3/com/2020082506/13L': No such file or directory
ROCOTO SAYS COMPLETION TASK DID NOT SUCCEED
STORM1.DONE, TRACKER OUTPUT DO NOT EXIST
hafs-PR_209_rt_hfsb_dev-13L-2020082506
/mnt/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/rocoto
Running PR_209_rt_hfsb_dev-13L-2020082506 configuration
08/11/23 13:48:23 UTC :: hafs-PR_209_rt_hfsb_dev-13L-2020082506.xml :: Fatal error: Document is empty at hafs-PR_209_rt_hfsb_dev-13L-2020082506.xml:1.
08/11/23 13:48:23 UTC :: hafs-PR_209_rt_hfsb_dev-13L-2020082506.xml :: Fatal error: Document is empty at hafs-PR_209_rt_hfsb_dev-13L-2020082506.xml:1.
/usr/bin/find: '/PR_209_rt_hfsb_dev/com/2020082506/13L': No such file or directory
ROCOTO SAYS COMPLETION TASK DID NOT SUCCEED
STORM1.DONE, TRACKER OUTPUT DO NOT EXIST
hafs-PR_209_rt_regional_atm-13L-2020082512
/mnt/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/rocoto
Running PR_209_rt_regional_atm-13L-2020082512 configuration
08/11/23 13:48:24 UTC :: hafs-PR_209_rt_regional_atm-13L-2020082512.xml :: Fatal error: Document is empty at hafs-PR_209_rt_regional_atm-13L-2020082512.xml:1.
08/11/23 13:48:25 UTC :: hafs-PR_209_rt_regional_atm-13L-2020082512.xml :: Fatal error: Document is empty at hafs-PR_209_rt_regional_atm-13L-2020082512.xml:1.
/usr/bin/find: '/PR_209_rt_regional_atm/com/2020082512/13L': No such file or directory
ROCOTO SAYS COMPLETION TASK DID NOT SUCCEED
STORM1.DONE, TRACKER OUTPUT DO NOT EXIST
```

i am not sure if this is related to changes in this PR or not. @mrinalbiswas @BinLiu-NOAA any ideas?

**Comment by ulmononian** [comment]
jet issues persists. seems like there are space issues in  `/lfs4/HFIP/hfv3gfs`:

```
2020082512/13L/storm1.vitals.allids: write unrenumbered vitals with all storm IDs
08/14 14:33:00.135 jlog (exhafs_launch.py:263) CRITICAL: exhafs_launch failed: [Errno 122] Disk quota exceeded
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/scripts/exhafs_launch.py", line 260, in <module>
    main()
  File "/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/scripts/exhafs_launch.py", line 209, in main
    conf=hafs.launcher.launch(infiles,cycle,stid,moreopts[i],case_root,
  File "/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/ush/hafs/launcher.py", line 576, in launch
    conf.gen_vitals(stid,cycling_interval,revit)
  File "/lfs4/HFIP/hfv3gfs/Cameron.Book/HAFS_wrk/save/PR_209/ush/hafs/launcher.py", line 1105, in gen_vitals
    with open(filename,'wt') as vitalsout:
OSError: [Errno 122] Disk quota exceeded
```

i cleared a bunch off stuff out, but as soon as the RTs start trying to write anything, the disk quota gets hit again.

here is the file quota info for `hfv3gfs`:

```
	Project: hfv3gfs
		FairShare=0.403 (41/57)
		Partition Access: ALL
		Available QOSes: batch,debug,novel,urgent,windfall

		Directory: /lfs4/HFIP/hfv3gfs DiskInUse=410553 GB, Quota=400000 GB, Files=18599361, FileQUota=80000000
```

**Comment by mrinalbiswas** [comment]
RTs passed on Orion and Hera.

**Review by KathrynNewman — APPROVED** [review]

**Comment by ulmononian** [comment]
@BinLiu-NOAA some jet RT updates:

1.  completed tests:`globnest_atm`, `globnest_static_atm`, `regional_atm`, `regional_atm_ocn`, `regional_static_C192s1n4_atm_3denvar` (06z cycle), and `regional_static_C192s1n4_atm_ocn_wav`
2. incomplete:`hfsa_dev_ww3` (died in 06z analysis task -> rebooted), `hfsb_dev` (06z forecast task in queue), `regional_static_C192s1n4_atm_3denvar` (12z cycle in queue)

**Comment by BinLiu-NOAA** [comment]
@ulmononian, since Jet is reserved for HFIP real-time experiments, it is very hard to get into the queue for HAFS RTs. Let's skip Jet for this PR. Thanks!

**Pull request merged**
