### PR TITLE
Sync HAFS submodules as of 05/12/2021

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
- Synced HAFS submodules with their corresponding authoritative branches as of 05/12/2021 including: hafs_utils.fd, hafs_gsi.fd, hafs_forecast.fd, hafs_post.fd.
- Fixed and updated HAFS FV3ATM-HYCOM coupling. Currently, by default, FV3ATM sends momentum flux, sensible and latent heat fluxes, net shortwave and longwave radiation fluxes, surface pressure, and precipitation rate to HYCOM; whereas HYCOM sends sea surface temperature to FV3ATM.

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
Again, appreciate it if you could help to run the regression tests as you helped previously!
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (xjet)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)
@ChunxiZhang-NOAA (ufs-weather-model level regression tests)

- To conduct the HAFS application level regression tests, you can:
A. Clone and checkout the branch, e.g.,
git clone -b feature/hafs_sync_20210512 --recursive https://github.com/hafs-community/HAFS.git ./hafs_sync_20210512
B. Build and install HAFS
cd hafs_sync_20210512/sorc
./install_hafs.sh # Afterward, please check or edit the ../parm/system.conf if needed.
C. Edit and run the cronjob driver as a cron job
cd ../rocoto
vi cronjob_hafs_rt.sh # make sure to use the correct platform and directory
./cronjob_hafs_rt.sh

Notes:
- The rocoto_utils.sh script under the rocoto dir can be used to check status for rocoto tasks and/or rewind failed rocoto tasks. Usage: ./rocoto_utils.sh [-a | -f | -r | -s] # Loop over all *.xml files
- The hafs_rt_status.sh script under the rocot dir can be used to check whether or not the HAFS regression tests run successfully. Usage: ./hafs_rt_status.sh
- As for the ufs-weather-model level regression tests, several cpld tests failed due to producing different results (can run through).

**Comment by ChunxiZhang-NOAA** [comment]
@BinLiu-NOAA   As you mentioned, the ufs-weather-model level regression tests are failed for some cpl runs, e.g., FAILED TESTS:
Test cpld_debug 028 failed in check_result failed
Test cpld_debug 028 failed in run_test failed
Test cpld_ca 008 failed in check_result failed
Test cpld_ca 008 failed in run_test failed
Test cpld_satmedmf 007 failed in check_result failed
Test cpld_satmedmf 007 failed in run_test failed
Test cpld_decomp 006 failed in check_result failed
Test cpld_decomp 006 failed in run_test failed
Test cpld_2threads 005 failed in check_result failed
Test cpld_2threads 005 failed in run_test failed
Test cpld_control 001 failed in check_result failed
Test cpld_control 001 failed in run_test failed
Test cpld_control_wave 027 failed in check_result failed
Test cpld_control_wave 027 failed in run_test failed
Test cpld_control_c192 009 failed in check_result failed
Test cpld_control_c192 009 failed in run_test failed
Test cpld_bmark 017 failed in check_result failed
Test cpld_bmark 017 failed in run_test failed
Test cpld_bmark_wave 024 failed in check_result failed
Test cpld_bmark_wave 024 failed in run_test failed
Test cpld_control_c384 013 failed in check_result failed
Test cpld_control_c384 013 failed in run_test failed

**Comment by BinLiu-NOAA** [comment]
Thanks @ChunxiZhang-NOAA for the model level regression tests and confirming there are some failed cpld tests!

I went ahead and conducted some further investigation, and it turns out the failed cpld tests (producing different results as the baseline) is due to the sea-ice point fix we introduced for fix HAFS FV3ATM-HYCOM coupling in GFS_surface_composites.F90.
```
#ifndef CICE6
                if (cplflx) islmsk_cice(i) = 2
#endif
              else
                cice(i)        = zero
                hice(i)        = zero
                flag_cice(i)   = .false.
                islmsk(i)      = 0
                islmsk_cice(i) = 0
              endif
              if (cice(i) < one) then
                wet(i) = .true. ! some open ocean
#ifdef CICE6
                if (.not. cplflx .and. icy(i)) tsfco(i) = max(tisfc(i), tgice)
#else
                if (icy(i)) tsfco(i) = max(tisfc(i), tgice)
#endif
```

Looks like this CICE6 CPP option is not safe/generalize enough to exclude/distinguish other applications from HAFS. We will need to figure out a more robust fix on this in the future.

Thanks!

Bin

**Comment by BinLiu-NOAA** [comment]
@evankalina, @panll, @mrinalbiswas, @JunghoonShin-NOAA, @LinZhu-NOAA, @BijuThomas-NOAA, if you are running the application level regression tests, please git pull to get [the above commit](https://github.com/hafs-community/HAFS/pull/68/commits/f99cd2e6202f96e625b71bad14ea7a5c9213a535). This will make sure the cmeps-based coupling regression test can go through. Thanks!

**Comment by BinLiu-NOAA** [comment]
@ChunxiZhang-NOAA and I had a working session this afternoon, and we implemented a new/better fix for dealing with the sea ice grid points in HAFS FV3ATM-HYCOM coupling  without an active sea ice component. A cplice namelist option (set as .false. for HAFS) in FV3 is added to deal with this situation. This is still a temporary solution for HAFS FV3ATM-HYCOM coupling. Some more coordination/generalization will be needed at the ufs-weather-model level to better support various coupled applications. But with this, it will currently does not affect the ufs-weather-model develop branch. All the model level regression tests can now pass by producing identical results to the baseline.

**Comment by BijuThomas-NOAA** [comment]
RT tests on Cray were completed successfully with a change in modulefile([3723685](https://github.com/hafs-community/HAFS/commit/3723685cab1792ab77e679653a03b98be890a933))

**Comment by panll** [comment]
RT tests on Hera have been completed successfully with Bin's latest commit. @BinLiu-NOAA @evankalina

**Comment by BinLiu-NOAA** [comment]
Thanks @BijuThomas-NOAA and @panll!

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA The regression tests completed successfully on WCOSSS DELL after updating the module file.

**Review by LinZhu-NOAA — DISMISSED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks @LinZhu-NOAA! After we get confirmation that HAFS application level regression tests can run through on Jet and Orion, we can then merge this PR.

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
The hafs_sync_20210512 branch regression test on Jet is successfully completed although Jet was slow during this week.
I have one thing to report about the globnest_grib2ab test. I had to reboot/rewind the forecast job for the globnest_grib2ab test because the forecast job failed due to MPI error (please refer to below). Interestingly, even though the forecast job for this test failed, it was displayed as “SUCCEEDED” in the rocoto workflow.
/mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafstmp/hafs_sync_20210512_rt_globnest_grib2ab/2020082512/13L/hafs_forecast.log.0
/mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafstmp/hafs_sync_20210512_rt_globnest_grib2ab/2020082512/13L/err.forecast (and out.forecast)

So I rebooted it (i.e., rocotoboot), and the forecast job failed again with the same MPI error. But after one more rewinding, the forecast job was successfully completed.

Except this, everything looked normal.
Thank you very much.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA @evankalina  RT passed on Orion.

**Review by evankalina — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks All! Merging this PR now.

**Pull request merged**
