### PR TITLE
Sync HAFS submodules with their authoritative branches as of 11/02/2021

### LINKED ISSUE #103: Sync HAFS submodules with their corresponding authoritative branches as of 11/02/2021
## Description
Sync HAFS submodules with their corresponding authoritative branches as of 11/02/2021.

## Related to
- hafs-community/hafs/pull/107

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes  
- Sync hafs_forecast.fd with its authoritative branch as of 11/03/2021
- Sync hafs_post.fd, hafs_utils.fd, hafs_gsi.fd with their corresponding authoritative branches as of 11/02/2021
- Remove the forecast build with the FV3_HAFS_v0_hwrf CCPP suite
- Update itag with namelist options needed by UPP in scripts/exhafs_atm_post.sh
- Use cp -r instead of cp -rp in scripts/exhafs_atm_prep.sh when copying the pregenerated gridfixdir
- Try to unify nems.configure.*.tmp
- Update ww3_ounp_spec.inp_tmpl needed by latest WW3 ww3_ounp

## Issues addressed (optional)
- hafs-community/hafs/issues/103

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

## Application-level regression test status  
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS Dell P3
- [x] WCOSS Cray

Again, as you helped previously, let's conduct the HAFS application/workflow level regression tests for this PR.
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (Jet)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)

BTW, @evankalina, it would be better if we can also try one or two HAFS CDEPS related tests on Orion for this PR.

### CODE REVIEW

**Comment by mrinalbiswas** [comment]
RT passed successfully on Orion

**Comment by BinLiu-NOAA** [comment]
> RT passed successfully on Orion

Thanks @mrinalbiswas! BTW, did you notice any forecast model slowdown on Orion. Yesterday, when I ran a test on Orion, the forecast model was very slow. I am not sure if that was just due to an Orion system hiccup.

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA 
Regression tests were successful on WCOSS-Cray

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
Regression tests on Jet failed because of the WW3 installation issue, and here is the ww3 build log file.
/mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafs_sync_20211102/sorc/logs/build_ww3_utils.log

According to the last line of this log file, the executable file "ww3_grib" was not generated in the hafs_forecast.fd/WW3/model/exe/ directory. So it is ww3_grib installation issue.

Thank you.

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA Regression tests completed successfully on WCOSS-Dell.

**Review by LinZhu-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
@JunghoonShin-NOAA, I looked at the ww3_grib build failure on Jet. It is due to a hpc-stack g2 library/module issue:
https://github.com/NOAA-EMC/hpc-stack/issues/329
which previously happened and was fixed on Orion. I am asking the hpc-stack team's help to fix this issue on Jet as well.

**Comment by BinLiu-NOAA** [comment]
Thanks, @LinZhu-NOAA and @BijuThomas-NOAA! Glad the regression tests passed on wcoss_cray and wcoss_dell_p3.

**Comment by panll** [comment]
Regression tests passed on Hera. @BinLiu-NOAA @evankalina

**Review by panll — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
> @JunghoonShin-NOAA, I looked at the ww3_grib build failure on Jet. It is due to a hpc-stack g2 library/module issue:
> [NOAA-EMC/hpc-stack#329](https://github.com/NOAA-EMC/hpc-stack/issues/329)
> which previously happened and was fixed on Orion. I am asking the hpc-stack team's help to fix this issue on Jet as well.

@JunghoonShin-NOAA the above mentioned hpc-stack g2 issue has been fixed. Please help to retry on Jet when you get a chance. Thanks!

**Comment by evankalina** [comment]
@BinLiu-NOAA I am working on testing HAFS-CDEPS on Orion and will let you know the result soon (hopefully on Tuesday).

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA I am working on testing HAFS-CDEPS on Orion and will let you know the result soon (hopefully on Tuesday).

@evankalina, Thanks for the heads-up! Hopefully the HAFS CDEPS coupling related tests can go through without issues.

**Comment by evankalina** [comment]
@BinLiu-NOAA After the small change that I committed yesterday, all of the CDEPS tests on Orion completed successfully.

**Review by evankalina — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks @evankalina for testing CDEPS and making these additional changes! Still waiting Jet RTs to go through. After that, this PR will be ready to merge. Thanks!

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
ww3_grib installation issue was solved.
On Jet, except three RT tests that have WW3 component, other experiments were successful. 
Three RT tests with WW3 component failed in the "wav_prep" task, and you can check 3 log files below.
Thank you.

/mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafstmp/hafs_sync_20211102_rt_regional_static_C192s1n4_atm_ocn_wav/2019082900/00L/hafs_wav_prep.log
/mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafstmp/hafs_sync_20211102_rt_regional_atm_ocn_wav/2020082512/13L/hafs_wav_prep.log
/mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafstmp/hafs_sync_20211102_rt_regional_static_atm_wav/2020082512/00L/hafs_wav_prep.log

**Comment by BinLiu-NOAA** [comment]
@JunghoonShin-NOAA, I looked at the failed job log file, and found this error in the ww3_grid.log file:
/mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafstmp/hafs_sync_20211102_rt_regional_static_C192s1n4_atm_ocn_wav/2019082900/00L/wav_prep/ww3init/ww3_grid.log
`Please verify that both the operating system and the processor support Intel(R) AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW, AVX512VL and CLWB instructions.`
However, when I try to run the ./ww3_grid executable on the front node, it can run through successfully. Still looking into this and trying to test from my side.

**Comment by BinLiu-NOAA** [comment]
> @JunghoonShin-NOAA, I looked at the failed job log file, and found this error in the ww3_grid.log file:
> /mnt/lfs4/HFIP/hwrfv3/Junghoon.Shin/hafstmp/hafs_sync_20211102_rt_regional_static_C192s1n4_atm_ocn_wav/2019082900/00L/wav_prep/ww3init/ww3_grid.log
> `Please verify that both the operating system and the processor support Intel(R) AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW, AVX512VL and CLWB instructions.`
> However, when I try to run the ./ww3_grid executable on the front node, it can run through successfully. Still looking into this and trying to test from my side.

@JessicaMeixner-NOAA, @aliabdolali, or @MatthewMasarik-NOAA, not sure if you have some insights/ideas why this is happening on Jet (other platforms are fine without issues). Is there any recent build option changes related? Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
@BinLiu-NOAA I don't run on jet so it's hard to know, looks like it doesn't like one of the compiler settings that waves is using though?  But it would be odd for it to run on the login node but not compute node?    Can you post the log on hera? (Sorry I tried to log into jet but failed to).  The only thing if it runs on the log in but not on compute, might be a memory issue?

**Comment by MatthewMasarik-NOAA** [comment]
Hi @BinLiu-NOAA , I think @JessicaMeixner-NOAA could be right regarding a potential memory issue.  I also do not have access to Jet, though would be happy to look at the ww3 log output.

**Comment by evankalina** [comment]
@BinLiu-NOAA @JessicaMeixner-NOAA @MatthewMasarik-NOAA Another possible thing to check is this tip from RDHPCS for compiling with Intel on Jet:

Compile for all Partitions: The following AVX option will allow the compiler to generate code that can be run on all current jet partitions, which should be the default to improve job turnaround and optimize system utilization:

-O3 -axSSE4.2,AVX,CORE-AVX2,CORE-AVX512  -align array64byte -ip

**Comment by JessicaMeixner-NOAA** [comment]
We do not add any jet specific compiler flags in WW3, see: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/bin/cmplr.env#L182-L204

Perhaps, that is needed?

**Comment by evankalina** [comment]
Yeah I think it could be worth a try, adding that string of AVX flags that RDHPCS mentions. If you want, I could try to add a stanza to the cmplr.env file and see if it builds, if @JunghoonShin-NOAA is willing to test the resulting executable in his experiment.

**Comment by evankalina** [comment]
Yeah I think it could be worth a try, adding that string of AVX flags that RDHPCS mentions. If you want, I could try to add a stanza to the cmplr.env file and see if it builds, if @JunghoonShin-NOAA is willing to test the resulting executable in his experiment.

**Comment by BinLiu-NOAA** [comment]
> We do not add any jet specific compiler flags in WW3, see: https://github.com/NOAA-EMC/WW3/blob/develop/model/bin/cmplr.env#L182-L204
> 
> Perhaps, that is needed?

@JessicaMeixner-NOAA, for the L182-L204 section, if I understand correctly, Jet turns out to use 
  else
    optc="$optc -xhost"
    optl="$optl -xhost"
  fi
If so, my understanding -xhost will not work for Jet, since Jet have different partitions/login nodes.

**Comment by JessicaMeixner-NOAA** [comment]
Try this branch of WW3: https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/jet it has the compiler specific flags @evankalina mentioned.

**Comment by BinLiu-NOAA** [comment]
> Try this branch of WW3: https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/jet it has the compiler specific flags @evankalina mentioned.

Thanks, @JessicaMeixner-NOAA! I am building and conducting a test with your bug/jet branch. Will report back on how it goes.

**Comment by BinLiu-NOAA** [comment]
@JessicaMeixner-NOAA, the test with your [bug/jet](https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/jet) went through properly.

Meanwhile, for the wav_prep task, there was another issue regarding the hpc-stack version wgrib2 (not being build with with netcdf option on Jet), see https://github.com/NOAA-EMC/hpc-stack/issues/278. With that, we have to switch to use another version of system installed wgrib2. I have just committed this change back to this PR branch.

In the meantime, @evankalina, does it sound good to you that we merge this PR as is for now. And we will fix WW3 coupling related configurations once the above WW3 bug fix was fixed/updated from the WW3 and ufs-weather-model sides.

Thanks!

**Comment by evankalina** [comment]
@BinLiu-NOAA Glad that this fix works. Yes, that sounds good to me. Otherwise, we would have to either make a hafs-community fork of WW3 or point to Jessica's branch, since we're currently pointing to the develop branch of the authoritative WW3 repo under NOAA-EMC.

**Comment by BinLiu-NOAA** [comment]
Thanks @evankalina! Ready to merge this PR. 

Again note, the WW3 coupling related configurations/RTs do not work on Jet, which will be fixed in a future update.

Thanks to All for conducting the HAFS application level regression tests and fixing/discussing the issues!

**Pull request merged**
