### PR TITLE
Sync HAFS submodules as of 09/09/2019 and add recent HAFS DA changes

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes  

- Sync HAFS submodules with their corresponding authoritative branches as of 09/09/2021, including: 
  - hafs_forecast.fd
  - hafs_utils.fd
  - hafs_post.fd (EMC_post has also been renamed as UPP)
  - hafs_gsi.fd
- HAFS application/workflow level changes to enable satellite (GOES-R and SSIMS) post-processing, by default satpost is set as .false. for now since inline satpost will need a future version of UPP library (from @LinZhu-NOAA)
- Recent HAFS DA system related upgrades from the feature/hafs_ensda branch, including
  - Upgrading crtm from 2.2.6 to 2.3.0 (from @lbi2018)
  - Updating hafs_convinfo.txt by changing rmsh from 9. to 12. for obstype 990-993 (radar radial wind), needed by HAFSv0.2D real-time experiment running on Jet (from @yonghuiweng)
  - Updated hafs_gsi.fd submodule with dual-resolution 3DEnVar bug fix and further consolidation (from OU collaborators and @TingLei-NOAA)

### Issues addressed

- hafs-community/HAFS/issues/94
- hafs-community/HAFS/issues/74
- hafs-community/HAFS/issues/42

## Tests conducted
HAFS application level tests ran through on Orion. A HAFS DA technical test with self-cycled ENSDA system also ran through on Orion.

## Application-level regression test status  
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS Dell P3
- [x] WCOSS Cray

Again, as you helped previously, let's start the HAFS application/workflow level regression tests:
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (Jet, we probably will skip Jet since it is occupied by the HFIP real-time parallel experiments under reservation)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)

### CODE REVIEW

**Comment by panll** [comment]
The regression tests passed on Hera. @BinLiu-NOAA @evankalina

**Review by panll — APPROVED** [review]

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA @evankalina 
RT tests were successful on WCOSS-Cray

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks, @panll and @BijuThomas-NOAA! Once @mrinalbiswas and @LinZhu-NOAA finish the regression tests on Orion and wcoss_dell_p3, we can then merge this PR.

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA RT tests passed successfully on Orion.

**Review by mrinalbiswas — APPROVED** [review]

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA Regression tests completed successfully on WCOSS-DELL.

**Review by LinZhu-NOAA — APPROVED** [review]

**Review by evankalina — APPROVED** [review]

**Pull request merged**
