### PR TITLE
Add CODE_STYLE.md for general coding/scripting guidance

### LINKED ISSUE #157: Add CODE_STYLE.md
## Description
Provide a clear and concise description of the requested feature/capability.
Add a CODE_STYLE.md file to provide some general guidance/suggestions at the HAFS application/workflow level.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Add a CODE_STYLE.md file, which was discussed among DTC/EMC code owners.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
Add a CODE_STYLE.md file to provide some general guidance/suggestions at the HAFS application/workflow level.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/157

## Contributors (optional)
If others worked on this PR besides the author, please include their user names here (using @Mention if possible).
DTC and EMC code owners.

## Tests conducted
Not Applicable.

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@panll, @KathrynNewman, I think we previously discussed on adding a CODE_STYLE.md file in HAFS repository. This is based on a draft we went through a few month ago. Please help to further modify and review and merge this PR back to HAFS develop branch. Thanks!

**Review by panll — APPROVED** [review]
Looks good to me, thanks! @BinLiu-NOAA

**Comment by BinLiu-NOAA** [comment]
@KathrynNewman, and/or @ZhanZhang-NOAA, please help review/approve this PR. If it looks good, we can then merge this PR. BTW, I am drafting a follow-up PR with HAFS application/workflow level script cleanups. Thanks!

**Review by KathrynNewman — APPROVED** [review]
Looks good. Thanks, @BinLiu-NOAA

**Comment by BinLiu-NOAA** [comment]
Thanks, @KathrynNewman!

**Pull request merged**
