### PR TITLE
Merge HAFSv0.2 configuration into develop and sync HAFS submodules as of 202107

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
This PR tries to:
- Bring the HAFSv0.2 configuration used in 2021 HFIP HAFS real-time parallel experiments back in HAFS develop branch
- Sync HAFS submodules including hafs_forecast.fd (as of 07/12/2021), and hafs_utils.fd (as of 07/09/2021), hafs_gsi.fd (as of 07/09/2021), and hafs_post.fd (as of 07/09/2021) with their corresponding authoritative branches.

And this PR addresses issues #72, #73, #64.

Notes:
- The HAFSv0.2 configuration were recently finalized for 2021 HFIP HAFSv0.2A real-time experiment based on the retrospective tests for 2019/2020 NATL storms. This HAFSv0.2A experiment also serves as the control experiment/configuration for the HAFSv0.2B/D/E real-time experiments. The development, testing and evaluation of the HAFSv0.2A configuration is one of the important HAFS development milestones.
- Thanks to @danrosen25, @uturuncoglu, and @ChunxiZhang-NOAA for helping solve the conflicts when syncing the support/HAFS branch with the latest ufs-weather-model develop branch.

Testing:

Again, appreciate it if you could help to run the regression tests as you helped previously!
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (Jet, we probably will skip Jet since it is occupied by the HFIP real-time parallel experiments under reservation)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)
@ChunxiZhang-NOAA (ufs-weather-model level regression tests)

To conduct the HAFS application level regression tests, you can:
A. Clone and checkout the branch, e.g.,
git clone -b feature/hafs_sync_202107 --recursive https://github.com/hafs-community/HAFS.git ./hafs_sync_202107
B. Build and install HAFS
cd hafs_sync_202107/sorc
./install_hafs.sh # Afterward, please check or edit the ../parm/system.conf if needed.
C. Edit and run the cronjob driver as a cron job
cd ../rocoto
vi cronjob_hafs_rt.sh # make sure to use the correct platform and directory
./cronjob_hafs_rt.sh

To run the ufs-weather-model level regression tests:
cd sorc/hafs_forecast.fd/tests
vi detect_machine.sh and update this line into export ACCNR=${ACCNR:-hurricane} or your own compute project name.
Launch the ufs-weather-model level regression tests
nohup ./rt.sh -e > rt.log 2>&1 &

### CODE REVIEW

**Comment by ChunxiZhang-NOAA** [comment]
The regression tests on ufs-weather-model level were finished successfully.

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by BijuThomas-NOAA** [comment]
The regression tests with the feature/hafs_sync_202107 branch were successful on WCOSS-CRAY

**Comment by LinZhu-NOAA** [comment]
The regression tests with the feature/hafs_sync_202107 branch were successful on WCOSS-DELL

**Review by LinZhu-NOAA — APPROVED** [review]

**Comment by linlin-pan** [comment]
The regression tests were successful on Hera with the feature/hafs_sync_202107  branch.

**Comment by BinLiu-NOAA** [comment]
Note: There is a known issue from the ufs-weather-model side: NOAA-EMC/fv3atm/issues/344, which changed the Time dimension and contents of the sfc_data.nc restart files. This broke the HAFS DA capability since DA/GSI need to read these sfc_data restart files. Fixing is ongoing from the ufs-weather-model side. And this HAFS DA capability will be restored next time when we sync ufs-weather-model develop branch after the fix. Currently, if you want to run the HAFS DA configurations/experiments, please keep using the feature/hafs_ensda branch instead.

**Comment by BinLiu-NOAA** [comment]
@mrinalbiswas, not sure if your application level regression tests go through on Orion successfully. If so, we are ready to merge this PR. Thanks!

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA The Orion tests are going very slow. The forecasts were on the queue for past three days. Now forecasts jobs are done. Post and products are running at different stages. I am hoping that they will be done by today. However, since the forecast jobs are done I am little confident that the tests will pass. So, you can go ahead with the merge, if needed. I will report any issues or report success when the tests are done on my end.

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA  RT on Orion passed.

**Review by mrinalbiswas — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks @mrinalbiswas!

**Pull request merged**
