### PR TITLE
augmented GDAS & long forecast (ensemble)

### PR DESCRIPTION
**Pull request by Kenta9638**
s1
s2
## Description of changes

**1. Mixed HAFS-GDAS error covariance**

  Please refer to the attached two slides.
  We implemented the new part highlighted with red boxes in the second slide.

- Convert GDAS grid to HAFS grid
_jobs/JHAFS_RST_GDAS_ENS
scripts/exhafs_atm_ic.sh_

- Replace GDAS ensemble mean with HAFS ensemble mean
_jobs/JHAFS_MIX_ENS_RECENTER
scripts/exhafs_mix_ens_recenter.sh_

- EnKF (or PF) update with the mixed HAFS-GDAS error covariance
_scripts/exhafs_enkf_hx.sh
scripts/exhafs_enkf.sh_

**2. Long forecast**

  We implemented long-term forecasts for the first 10 members of the analysis ensemble.
  We introduced config.NHRS_ENS_LONG, which is a different variable from config.NHRS_ENS.
  _jobs/JHAFS_ATM_POST_LONG_ENS
  jobs/JHAFS_FORECAST_LONG_ENS
  jobs/JHAFS_PRODUCT_LONG_ENS
  scripts/exhafs_forecast.sh
  scripts/exhafs_product.sh_

**3. The local particle filter**

  We changed the name list for the local PF.
  _parm/analysis/gsi/enkf.nml.tmp
  scripts/exhafs_enkf.sh_

**4.** 
parm/hafs.conf
parm/hafs_basic.conf
parm/hafs_holdvars.conf
parm/hafs_holdvars.txt
rocoto/hafs_workflow.xml.in
rocoto/run_hafs.py
rocoto/sites/orion.ent

## Tests conducted
Experiments have been conducted in the following directory.
**/work/noaa/aoml-hafsda/kurosawa/WORK/HAFS_RUN/TEST_20211021/rocoto**

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet
- [ ] Hera
- [ ] Orion
- [ ] WCOSS Dell P3
- [ ] WCOSS Cray

### CODE REVIEW

**Comment by evankalina** [comment]
@Kenta9638 Thanks for submitting this PR, and especially for the detailed explanation of its capabilities in the PR description! I will start looking through it soon. Are you by chance available to join us during the next HAFS developers committee meeting (April 18 at 12 ET)? It would be nice to have at least a brief discussion about this PR to get everyone's thoughts.

**Comment by Kenta9638** [comment]
Yes, I'll join the next HAFS developers meeting.
Kenta

**Comment by BinLiu-NOAA** [comment]
@Kenta9638, and @panll, since this PR is not yet ready to go back to HAFS develop branch. I was thinking of closing this PR at this moment. Thanks!

**Comment by BinLiu-NOAA** [comment]
Close this PR at this moment. Can revisit this later on.

**Pull request closed without merging**
