### PR TITLE
Bring in feature/hafs.v2.0.1 back to develop

### LINKED ISSUE #284: Bring in HAFSv2.0.1 real-time parallel experiment related developments back to HAFS develop
## Description
Provide a clear and concise description of the requested feature/capability.
Merge HAFSv2.0.1 real-time parallel experiment related developments from the feature/hafs.v2.0.1 branch back to HAFS develop branch.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.

Create a pull request to merge feature/hafs.v2.0.1 branch back to develop branch.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/299

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
Bring in the HAFSv2.0.1 development and configurations used by 2024 HFIP real-time parallel experiments back to HAFS develop branch. More details/configurations for 2024 HFIP HAFSv2.0.1A and B real-time parallel experiments can be found below.
  * HAFSv2.0.1A configurations
    - System and infrastructure
      - Synced HAFS submodules with their latest authoritative branches as of 07/03/2024
    - Vortex initialization and data assimilation upgrades
      -  Improved vortex initialization with Pmin adjustment improvements (@JunghoonShin-NOAA)
      - Storm-following 3DIAU in innercore DA (@XuLu-NOAA)
      - Assimilate more obs and use new crtm/2.4.0.1 (@yonghuiweng and @JingCheng-NOAA)
    - Physics and dynamics improvements
      - Adopt the scale-adaptive convective cloud water calculation in saSAS and reduce the minimum background diffusivity in the inversion layer near the PBL top from xkinv1=0.4 to xkinv1=0.15 (From Lisa Bengtsson, details can be found [#2340](https://github.com/ufs-community/ufs-weather-model/pull/2340))
      - Unify and turn on progsigma for saSAS for all the TC basins
      - Use the Exponential-Random (instead of Maximum-Random) cloud overlap approach (iovr=5) in RRTMG (AER/DTC/EMC)
      - Unify and use hord=1 with lim_fac of 3.0
    - Coupling
      - Use new RTOFSv2.5 input data
      - Use MOM6 ePBL mixed layer scheme with the OM4 related options (@MariaAristizabal-NOAA) 
        - EPBL_MSTAR_SCHEME = "OM4"
  * HAFSv2.0.1B configurations
    - System and infrastructure
      - Synced HAFS submodules with their latest authoritative branches as of 07/03/2024
    - Vortex initialization and data assimilation upgrades
      -  Improved vortex initialization with Pmin adjustment improvements (@JunghoonShin-NOAA)
      - Storm-following 3DIAU in innercore DA (@XuLu-NOAA)
      - Assimilate more obs and use new crtm/2.4.0.1 (@yonghuiweng and @JingCheng-NOAA)
    - Physics and dynamics improvements
      - Use the new Tiedtke CP scheme with increased entrainment/detrainment coefficients (@AndrewHazelton)
      - Reduce elmx/rlmx from 75 to 60 (@AndrewHazelton)
      - Use hord=1 with lim_fac of 2.6
    - Coupling
      - Use new RTOFSv2.5 input data
      - Use MOM6 ePBL mixed layer scheme (@hyunsookkim-NOAA and @AndrewHazelton)
        - EPBL_MSTAR_SCHEME = "CONSTANT"
        - USE_PSURF_IN_EOS=True (instead of False)
        - EQN_OF_STATE = "JACKETT_06" (instead of WRIGHT)
        - FOX_KEMPER_ML_RESTRAT_COEF = 1.0 (instead of 0.0)
        - KAPPA_SHEAR_ITER_BUG = False (instead of True)

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/284

## Contributors (optional)
If others worked on this PR besides the author, please include their user names here (using @Mention if possible).
EMC hurricane project team with lots of collaborators from the UFS Hurricane Application Team.

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

Technical, retrospective, and real-time parallel testing were conducted.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] Hercules
- [x] WCOSS2

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@JunghoonShin-NOAA, @nriveratorres-NOAA, @LinZhu-NOAA, @ChuankaiWang-NOAA, could you please help to cover the regression tests for this PR on the following platforms, respectively?
Jet: @JunghoonShin-NOAA
Orion: @nriveratorres-NOAA 
Hercules: @ChuankaiWang-NOAA 
Hera: @LinZhu-NOAA 
WCOSS2: @BinLiu-NOAA 

Thanks!

**Comment by BinLiu-NOAA** [comment]
Regression tests on WCOSS2 have already passed successfully without issues.

**Comment by ChuankaiWang-NOAA** [comment]
Using batch instead of windfall to avoid queueing.
RT passed on Hercules.

**Comment by nriveratorres-NOAA** [comment]
Regression tests passed successfully on Orion

**Review by nriveratorres-NOAA — APPROVED** [review]

**Comment by JunghoonShin-NOAA** [comment]
All regression tests completed successfully on Jet. But the ocean input data for the test case (2020 Laura 13L) does not exist on Jet anymore, and so I used Hurricane Lee as a test case.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Review by ChuankaiWang-NOAA — APPROVED** [review]

**Comment by BijuThomas-NOAA** [comment]
Since Lin is on travel, I conducted the RT on Hera. All regression tests were completed successfully on Hera

**Comment by BinLiu-NOAA** [comment]
@ZhanZhang-NOAA or @KathrynNewman We need another approval from the repo owners before merging this PR. Appreciated it if you get a chance to review and approve from your end. Thanks!

**Review by KathrynNewman — APPROVED** [review]
Approving changes bringing feature/hafs.v2.0.1 to develop. RTs passed on all platforms.

**Pull request merged**
