### PR TITLE
Incorporate WW3 coupling and support various atm-ocn-wav coupling configurations in the HAFS application/workflow

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes  
- Add WW3 wave-coupling related tasks/scripts in the HAFS application/workflow.
- Unify and HAFS application support for various different two-way, one-way, side-by-side, cmeps or nuopc based coupling configurations for the HAFS atm-ocn-wav (FV3-HYCOM-WW3) system, including:
  - hafs_a2o2a_a2w2a: CMEPS based two-way atm-ocn and two-way atm-wav coupling
  - hafs_a2o2a_a2w: CMEPS based two-way atm-ocn and one-way atm2wav coupling
  - hafs_a2o_a2w2a: CMEPS based one-way atm2ocn and two-way atm-wav coupling
  - hafs_a2o_a2w: CMEPS based one-way atm2ocn and one-way atm2wav coupling
  - hafs_abo_abw: CMEPS based side-by-side atm-ocn-wav run without coupling
  - hafs_nuopc_abo_abw: NUOPC based side-by-side atm-ocn-wav run without coupling
  - hafs_a2o2a: CMEPS based two-way atm-ocn coupling
  - hafs_a2o: CMEPS based one-way atm2ocn coupling
  - hafs_o2a: CMEPS based one-way ocn2atm coupling
  - hafs_abo: CMEPS based side-by-side atm-ocn run without coupling
  - hafs_nuopc_abo: NUOPC based side-by-side atm-ocn run without coupling
  - hafs_nuopc_a2o2a:  NUOPC based two-way atm-ocn coupling
  - hafs_a2w2a: CMEPS based two-way atm-wav coupling
  - hafs_a2w: CMEPS based one-way atm2ocn coupling
  - hafs_w2a: CMEPS based one-way wav2atm coupling
  - hafs_abw: CMEPS based side-by-side atm-wav run without coupling
- Examples for the above different configurations can be found from rocoto/cronjob_hafs_cpl.sh
- Update the HAFS application/workflow standard regression tests, which now include:
  - Regional static NATL basin-focused configuration with atm-ocn coupling
  - Regional static NATL basin-focused configuration with atm-wav coupling
  - Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling
  - Regional storm-focused configuration with atm-ocn-wav coupling
  - Regional storm-focused configuration (atm-only) with GFS grib2ab format IC/BC
  - Global-nesting static NATL basin-focused configuration (atm-only)
  - Global-nesting storm-focused configuration (atm-only) with GFS grib2ab format IC/BC

## Issues addressed:
- hafs-community/HAFS/issues/96

## Contributors:
@BinLiu-NOAA, @uturuncoglu, @danrosen25, @JessicaMeixner-NOAA, @hyunsookkim-NOAA, @BijuThomas-NOAA, @MariaAristizabal-NOAA, @JohnSteffen-NOAA, @ChunxiZhang-NOAA, @aliabdolali, etc.

## Tests conducted
- HAFS application level regression tests passed on Orion
- Technical tests and sanity checks for 16 different two-way, one-way, side-by-side, cmeps or nuopc based coupling configurations were conducted on Orion

## Application-level regression test status  
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS Dell P3
- [x] WCOSS Cray

As you helped previously, let's start the HAFS application/workflow level regression tests:
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (Jet, we probably will skip Jet since it is occupied by the HFIP real-time parallel experiments under reservation)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)

### CODE REVIEW

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA RTs passed successfully on Orion.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA RTs passed successfully on Orion.

Thanks @mrinalbiswas!

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA, All regression tests except **_Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling_** succeeded on WCOSS-Cray.

The atm_ic task(Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling) failed with the error message:

```
20210925 160617.715 ERROR            PET270 ESMF_FieldRegrid.F90:2719 ESMF_FieldRegridGetIwts Invalid argument  - - can't currently regrid a grid that contains a DE of width less than 2
20210925 160617.716 ERROR            PET270 ESMF_FieldRegrid.F90:1066 ESMF_FieldRegridStoreNX Invalid argument  - Internal subroutine call returned Error
20210925 160617.716 ERROR            PET270 atmosphere.F90:361 Invalid argument  - Passing error in return code
```
Let me know if anybody is familiar with this error?. 
Cray Location: /gpfs/hps3/ptmp/Biju.Thomas/hafs_coupleww3_rt_regional_static_C192s1n4_atm_ocn_wav/2019082900

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA Regression tests completed successfully on WCOSS-DELL.

**Review by LinZhu-NOAA — DISMISSED** [review]

**Comment by BijuThomas-NOAA** [comment]
> @BinLiu-NOAA, All regression tests except **_Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling_** succeeded on WCOSS-Cray.
> 
> The atm_ic task(Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling) failed with the error message:
> 
> ```
> 20210925 160617.715 ERROR            PET270 ESMF_FieldRegrid.F90:2719 ESMF_FieldRegridGetIwts Invalid argument  - - can't currently regrid a grid that contains a DE of width less than 2
> 20210925 160617.716 ERROR            PET270 ESMF_FieldRegrid.F90:1066 ESMF_FieldRegridStoreNX Invalid argument  - Internal subroutine call returned Error
> 20210925 160617.716 ERROR            PET270 atmosphere.F90:361 Invalid argument  - Passing error in return code
> ```
> 
> Let me know if anybody is familiar with this error?.
> Cray Location: /gpfs/hps3/ptmp/Biju.Thomas/hafs_coupleww3_rt_regional_static_C192s1n4_atm_ocn_wav/2019082900

BTW on Cray,  We use esmf/8.0.0(/gpfs/hps3/emc/nems/noscrub/emc.nemspara/soft/esmf/8.0.0/lib/esmf.mk). Worth try with a different later version?

**Comment by BinLiu-NOAA** [comment]
> > @BinLiu-NOAA, All regression tests except **_Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling_** succeeded on WCOSS-Cray.
> > The atm_ic task(Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling) failed with the error message:
> > ```
> > 20210925 160617.715 ERROR            PET270 ESMF_FieldRegrid.F90:2719 ESMF_FieldRegridGetIwts Invalid argument  - - can't currently regrid a grid that contains a DE of width less than 2
> > 20210925 160617.716 ERROR            PET270 ESMF_FieldRegrid.F90:1066 ESMF_FieldRegridStoreNX Invalid argument  - Internal subroutine call returned Error
> > 20210925 160617.716 ERROR            PET270 atmosphere.F90:361 Invalid argument  - Passing error in return code
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if anybody is familiar with this error?.
> > Cray Location: /gpfs/hps3/ptmp/Biju.Thomas/hafs_coupleww3_rt_regional_static_C192s1n4_atm_ocn_wav/2019082900
> 
> BTW on Cray, We use esmf/8.0.0(/gpfs/hps3/emc/nems/noscrub/emc.nemspara/soft/esmf/8.0.0/lib/esmf.mk). Worth try with a different later version?

@BijuThomas-NOAA, I saw this kind of errors before. Can you try to reduce the number of PEs to run atm_ic/lbc tasks for this low-resolution RT? Thanks!

**Comment by BijuThomas-NOAA** [comment]
> > > @BinLiu-NOAA, All regression tests except **_Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling_** succeeded on WCOSS-Cray.
> > > The atm_ic task(Regional low-resolution static NATL basin-focused configuration with atm-ocn-wav coupling) failed with the error message:
> > > ```
> > > 20210925 160617.715 ERROR            PET270 ESMF_FieldRegrid.F90:2719 ESMF_FieldRegridGetIwts Invalid argument  - - can't currently regrid a grid that contains a DE of width less than 2
> > > 20210925 160617.716 ERROR            PET270 ESMF_FieldRegrid.F90:1066 ESMF_FieldRegridStoreNX Invalid argument  - Internal subroutine call returned Error
> > > 20210925 160617.716 ERROR            PET270 atmosphere.F90:361 Invalid argument  - Passing error in return code
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Let me know if anybody is familiar with this error?.
> > > Cray Location: /gpfs/hps3/ptmp/Biju.Thomas/hafs_coupleww3_rt_regional_static_C192s1n4_atm_ocn_wav/2019082900
> > 
> > 
> > BTW on Cray, We use esmf/8.0.0(/gpfs/hps3/emc/nems/noscrub/emc.nemspara/soft/esmf/8.0.0/lib/esmf.mk). Worth try with a different later version?
> 
> @BijuThomas-NOAA, I saw this kind of errors before. Can you try to reduce the number of PEs to run atm_ic/lbc tasks for this low-resolution RT? Thanks!

@BinLiu-NOAA, Thanks it worked!

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA and @evankalina, RT tests on Cray were successful

**Review by BijuThomas-NOAA — DISMISSED** [review]

**Comment by panll** [comment]
The regression tests passed on Hera with some minor issues: HAFS_rt_regional_static_atm_ocn failed at first time at the forecast part due to time limit; however, it passed at the second time run without any changes. @BinLiu-NOAA @evankalina

**Review by panll — DISMISSED** [review]

**Comment by BinLiu-NOAA** [comment]
> > @BijuThomas-NOAA, I saw this kind of errors before. Can you try to reduce the number of PEs to run atm_ic/lbc tasks for this low-resolution RT? Thanks!
> 
> @BinLiu-NOAA, Thanks it worked!

@BijuThomas-NOAA, Glad it worked. After you reduce the node/PE number for the atm_ic for the low-resolution RT, can the high-resolution regional RT still run through the atm_ic job? If so, please commit your change of rocoto/sites/wcoss_cray.ent back to this branch. Thanks!

**Comment by BinLiu-NOAA** [comment]
Thanks @BijuThomas-NOAA for testing and committing this change!

And thanks to @mrinalbiswas, @panll, @LinZhu-NOAA, and @BijuThomas-NOAA for conducting the HAFS application regression tests!

I thinks this PR is ready to be merged now! Need two review approvals though.

Thanks!

Bin

**Review by evankalina — APPROVED** [review]

**Review by LinZhu-NOAA — APPROVED** [review]

**Pull request merged**
