### PR TITLE
Update mpiserial

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description of changes
The mpiserial sleep loop on WCOSS2 was unable to sleep less than one second (default is 0.5) because gettimeofday always returned 0 for the microsecond part of the time. This updates the code to use clock_gettime, if available, and falls back to gettimeofday otherwise. Also, the default sleep time is now 1 second.

## Issues addressed (optional)
None?

## Dependencies (optional)
None.

## Contributors (optional)
@BinLiu-NOAA contacted me about mpiserial problems, and I tracked it down to two problems, one was this code issue. The other was that the communal version of mpiserial had been built wrong.

## Tests conducted
HAFS atmosphere graphics.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [ ] Jet
- [ ] Hera
- [ ] Orion
- [ ] WCOSS2

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@SamuelTrahanNOAA, since your updates and branch is based on the production/hafs.v1 branch, could you please create the PR and merge your changes back on top of the production/hafs.v1 branch instead? Eventually, this change will go back to the develop branch when the production/hafs.v1 branch is merged back to develop. Thanks!

**Comment by SamuelTrahanNOAA** [comment]
> merge your changes back on top of the production/hafs.v1 branch instead

I just changed it as you requested, @BinLiu-NOAA

**Review by BinLiu-NOAA — APPROVED** [review]
Thanks for help to fix this mpiserial issue on WCOSS2!

**Comment by BinLiu-NOAA** [comment]
No application level RTs will be done now. Those will be conducted when the production/hafs.v1 branch goes back to the develop branch.

**Pull request merged**
