### PR TITLE
Bring in HAFSv2 related developments and configurations back into develop

### LINKED ISSUE #261: Bring HAFSv2 developments and upgrades back into HAFS develop branch
## Description
Provide a clear and concise description of the requested feature/capability.
HAFSv2 upgrades have been finalized, and HAFSv2 package delivery is planned/targeted early April, 2024. With that, we plan to bring in HAFSv2 related developments and upgrades to HAFS develop branch. 

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Create the feature/hafsv2_merge branch from the production/hafs.v2 branch (feature/hafsv2_final) branch, and then create a PR to merge feature/hafsv2_merge branch back to HAFS develop branch.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
Bring in the HAFSv2 related developments back to HAFS develop branch.
More details about HAFSv2 upgrade can be found: [doc/Release_Notes.hafs.v2.0.0.md](https://github.com/hafs-community/HAFS/blob/feature/hafsv2_merge/doc/Release_Notes.hafs.v2.0.0.md)

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/261

## Contributors (optional)
If others worked on this PR besides the author, please include their user names here (using @Mention if possible).
The UFS Hurricane Application Team.

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

Three year retrospective tests conducted during HAFSv2 testing and evaluation process. Technical testing conducted with this latest feature/hafsv2_merge branch.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] Hercules
- [x] WCOSS2

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
For the HAFS application level regression tests, please help to cover the following platforms, respectively.

- WCOSS2: @LinZhu-NOAA 
- Jet: @BinLiu-NOAA 
- Hera: @BijuThomas-NOAA 
- Orion: @nriveratorres-NOAA
- Hercules: @ChuankaiWang-NOAA 

Please feel free to let us know if you are not available to conduct the RTs, we can try to ask others to run to speed up this PR. Much appreciated! Thanks!

`git clone -b feature/hafsv2_merge --recursive https://github.com/hafs-community/HAFS.git ./`

**Comment by BinLiu-NOAA** [comment]
HAFS application level RTs passed on Jet.

**Comment by BijuThomas-NOAA** [comment]
RT passed on Hera

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by nriveratorres-NOAA** [comment]
RT passed on Orion

**Comment by LinZhu-NOAA** [comment]
HAFS RT passed on WCOSS2.

**Review by LinZhu-NOAA — APPROVED** [review]

**Comment by ChuankaiWang-NOAA** [comment]
RT passed on Hercules.

**Review by ChuankaiWang-NOAA — APPROVED** [review]

**Review by nriveratorres-NOAA — APPROVED** [review]

**Review by ZhanZhang-NOAA — APPROVED** [review]
Approve

**Pull request merged**
