### PR TITLE
Bring HAFSv0.3.0 series developments back to HAFS develop branch

### LINKED ISSUE #136: Merge HAFSv0.3.0 developments back to HAFS develop branch
## Description
As we now have the HAFSv0.3 configurations finalized for 2022 hurricane season real-time experiments, we would like to bring the HAFSv0.3 series developments back to HAFS develop branch.

## Proposed solution
Merge the feature/hafs.v0.3.0 branch back to the develop branch.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>
- dependent upon ufs-community/ufs-weather-model/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
Merge the finalized HAFSv0.3 configurations, which were used for 2022 hurricane season real-time experiments, back to HAFS develop branch.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/136

## Contributors (optional)
The UFS-HAFS application team.

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?
This branch was used by the HFIP HAFSv0.3A/S real-time parallel experiments. Also, various technical and regression tests were conducted using this branch.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [ ] Hera
- [x] Orion
- [x] WCOSS2

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
As usual, please help to conduct the HAFS application/workflow level regression tests for this PR.
@panll (Hera)
@mrinalbiswas (Orion)
@JunghoonShin-NOAA (Jet)
@BijuThomas-NOAA (wcoss2)

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA
GFS IC/BC missing for  2019082900 on WCOSS2.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA GFS IC/BC missing for 2019082900 on WCOSS2.

@BijuThomas-NOAA, I am transferring the 20190829 input data on WCOSS2 from dogwood to cactus now. Should be there in a few hours.

**Comment by panll** [comment]
@BinLiu-NOAA The RT tests on Hera passed for all the runs except for HAFS_rt_regional_mvnest_vida-13L-2020082506 at analysis merge part. The error message is:
forrtl: severe (174): SIGSEGV, segmentation fault occurred
The log can be found at: /scratch1/BMC/dtc-hwrf/Linlin.Pan/hafs/10022022/hafs0.3.0/ scrub/HAFS_rt_regional_mvnest_vida/2020082506/13L/analysis_merge/datool.fv_core.res.step1.log
Any comments or suggestions? thanks!

**Comment by BinLiu-NOAA** [comment]
@panll, you can give it a try with a larger memory saying <memory>80G</memory> to see if it can go through. - Bin

**Comment by panll** [comment]
@BinLiu-NOAA I tried the larger memory setting (e.g., 80G). It still fails. Thanks!

**Comment by BijuThomas-NOAA** [comment]
> 

@BinLiu-NOAA 
Thanks, Please transfer RTOFS files as well for 2019082900

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA Thanks, Please transfer RTOFS files as well for 2019082900
@BijuThomas-NOAA, RTOFS files are also on Cactus for 2019082900 now.

**Comment by BijuThomas-NOAA** [comment]
@BinLiu-NOAA, The regression tests on WCOSS2 completed successfully.

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA I have an updated hafs_rt_status.sh script. The old one doesn't work with parent directory names that have "." in them. Also, the old output files are no more present with the newer versions. Do you want me to commit the file to the feature branch?

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA  The regression tests on Orion completed successfully.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA I have an updated hafs_rt_status.sh script. The old one doesn't work with parent directory names that have "." in them. Also, the old output files are no more present with the newer versions. Do you want me to commit the file to the feature branch?

@mrinalbiswas, yes, please help to commit this and push back to this feature/hafs.v0.3.0 branch.

**Comment by BinLiu-NOAA** [comment]
Thanks, @BijuThomas-NOAA and @mrinalbiswas! Glad that the HAFS application regression tests went through successfully on WCOSS2 and Orion.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA I tried the larger memory setting (e.g., 80G). It still fails. Thanks!

@panll, not sure why this job cannot run through on Hera but can run through successfully on Orion. @BijuThomas-NOAA and @yonghuiweng, could you please help to take a look at this when you get a chance. Thanks!

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
I finally completed the regression tests on Jet successfully.
To run the forecast jobs for the Jet regression tests, I reduced the requested wall time from 7 hours 59 minutes to 50 minutes in sites/xjet.ent. By using this method, the forecast jobs on Jet can be run without much delay.
Thank you.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks, @JunghoonShin-NOAA! Glad that the HAFS application level regression tests went through successfully on Jet.

**Comment by BinLiu-NOAA** [comment]
@panll, for the HAFS_rt_regional_mvnest_vida-13L-2020082506 regression test's analysis merge job failure on Hera, based on @yonghuiweng and @BijuThomas-NOAA's investigation, it might be related to the intel compiler version. Since we will have to update to use the newer intel compiler version soon (following the ufs-weather-model), we can ignore this failure for this PR, and will revisit this for the next PR (#141) when syncing HAFS submodule with their latest authoritative branches.

**Comment by BinLiu-NOAA** [comment]
@KathrynNewman, @ZhanZhang-NOAA, I think this PR is ready to merge. We need another owner's review and approval. Please review and approve at your convenience. Thanks!

P.S., @KathrynNewman, since Evan left, who shall we propose to add as the DTC side HAFS repository co-owner to replace Evan?

**Review by panll — APPROVED** [review]

**Comment by panll** [comment]
@BinLiu-NOAA The pull request is approved. I can replace Evan as DTC GSL side HAFS repository co-owner. Thanks! @KathrynNewman @ZhanZhang-NOAA

**Review by KathrynNewman — APPROVED** [review]
PR reviewed and approved. @BinLiu-NOAA - I agree, @panll should be the second HAFS repository co-owner from the DTC. Thanks!

**Comment by BinLiu-NOAA** [comment]
Thanks, @KathrynNewman and @panll! Merging this PR now.

**Pull request merged**
