### PR TITLE
Bring in the HAFSv1 final configurations HFSA and HFSB

### LINKED ISSUE #42: Check and update HAFS grib2 products
Check and compare HAFS grib2 output fields with those from HWRF as well as those from GFS and FV3CAM. Since HAFS is FV3 based, we may or may not be able to output every field as from HWRF. Also, we may try to follow GFS for those fields common to GFS and HAFS.

### LINKED ISSUE #144: Add the capability of using the new UGWP scheme and enable its support for the moving nesting configuration
## Description
Provide a clear and concise description of the requested feature/capability.
Upgrade to the new UGWP scheme (which can also reproduce the existing old ugwp scheme when setting namelist option properly). 

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Workflow script changes are needed to generate GSL orography files.
Developments are needed to support the HAFS moving-nesting configuration properly.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #149: Extend the north boundary of the HYCOM ocean domain
## Description
Provide a clear and concise description of the requested feature/capability.
Currently, the HYCOM ocean domain's (e.g., HYCOM NHC domain used in HAFSv0.3A/S) north boundary is at ~ 45 degree N. And based on previously discussions, we would like to extend the HYCOM ocean domain northward to ~47 degree North or higher.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Extend the HYCOM ocean domain northward to ~47 degree N.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #161: Explore using VIIRS vegetation type in HAFS
## Description
Provide a clear and concise description of the requested feature/capability.
Explore using VIIRS vegetation type in HAFS. See related UFS_UTILS PR (ufs-community/UFS_UTILS/pull/699) and issue (ufs-community/UFS_UTILS/issues/698).

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?
@BantwaleEnyew-NOAA will work on this.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #174: Bring the HAFSv1 final configurations back to develop
## Description
The two HAFSv1 configurations HFSA and HFSB are now finalized. Retrospective tests were done for the past three hurricane seasons (2020-2022) for NHC domains. We would like to bring the final configuration back to HAFS develop branch.

## Proposed solution
Merge the feature/hafsv1_final branch back to the develop branch.

## Related to (optional)
- addressed by hafs-community/hafs/pull/175

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
Merge the feature/hafsv1_final branch back to HAFS develop branch, which is the branch/version used for HAFSv1 final retrospective tests for both HFSA and HFSB configurations.

## Issues addressed (optional)
- fixes hafs-community/HAFS/issues/174
- fixes hafs-community/HAFS/issues/161
- fixes hafs-community/HAFS/issues/149
- fixes hafs-community/HAFS/issues/144
- fixes hafs-community/HAFS/issues/42

## Contributors (optional)
Lots of developers from the UFS Hurricane Application Team. See more details in the actual commit log/history. We will keep the commit log for this PR.

## Tests conducted
Retrospective and technical tests were conducted on all the currently supported platforms.

## Application-level regression test status
- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS2

Please help to conduct the HAFS application/workflow level regression tests for this PR on the corresponding supported platforms. Thanks!
@mrinalbiswas (Orion)
@panll (Hera)
@BijuThomas-NOAA (Jet)
@JunghoonShin-NOAA (WCOSS2)

### CODE REVIEW

**Comment by panll** [comment]
Tested on Hera. All RT tests passed with 6 nodes and 20 processors on each node for atm_post. The atm_post will crash on Hera with 3 nodes and 40 processors on each node for some RT tests (e.g. regional_static_atm_wav, regional_static_atm_ocn)

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin, all regression tests on Cactus-WCOSS2 were completed successfully. (I tested it before the production switch)
Thank you.

**Comment by BinLiu-NOAA** [comment]
> Tested on Hera. All RT tests passed with 6 nodes and 20 processors on each node for atm_post. The atm_post will crash on Hera with 3 nodes and 40 processors on each node for some RT tests (e.g. regional_static_atm_wav, regional_static_atm_ocn)

@panll, Great that the RTs passed on Hera. Also, for the atm_post resource change on Hera, could you please help to commit the change back to this PR branch? Thanks!

**Comment by BinLiu-NOAA** [comment]
> Hello Bin, all regression tests on Cactus-WCOSS2 were completed successfully. (I tested it before the production switch) Thank you.

Thanks, @JunghoonShin-NOAA!

**Comment by panll** [comment]
PR is submitted. @BinLiu-NOAA

**Comment by BijuThomas-NOAA** [comment]
RT passed on Jet

**Review by panll — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
@mrinalbiswas Waiting for Orion RT status, otherwise ready to merge. Thanks!

**Comment by mrinalbiswas** [comment]
RTs passed on Orion!!

**Review by mrinalbiswas — APPROVED** [review]

**Review by KathrynNewman — APPROVED** [review]

**Pull request merged**
