### PR TITLE
Sync HAFS submodules and bring in HAFSv1 baseline configurations

### LINKED ISSUE #141: Sync HAFS submodules as of 202210
## Description
Provide a clear and concise description of the requested feature/capability.
Sync HAFS submodules (hafs_forecast.fd, hafs_post.fd, hafs_utils.fd, hafs_gsi.fd, etc.) with their latest authoritative branches as of 202210.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Sync HAFS submodules and conduct HAFS application level regression tests.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #142: Remove support for WCOSS Cray and Dell_p3
## Description
Provide a clear and concise description of the requested feature/capability.
As WCOSS2 replaced WCOSS Cray and WCOSS Dell_p3, need to remove the HAFS application support for WCOSS Cray and WCOSS Dell_p3.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Update/remove the related module files and scripts to disable the support for WCOSS Cray and Dell_p3 (including for the related submodules). 

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #143: Update to use .lua style modulefiles
## Description
Provide a clear and concise description of the requested feature/capability.
Convert modulefiles to .lua format on WCOSS2, hera, jet, orion, including for both HAFS application level and related submodule components (e.g., hafs_graphics.fd, hafs_tracker.fd).

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
See examples from ufs-community/ufs-weather-model/pull/1399

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #145: Enable using upoff as a config and namelist option
## Description
Provide a clear and concise description of the requested feature/capability.
- Add upoff as a namelist option for ufs-weather-model/fv3atm/fv3dycore, which can potentially alleviate the model numerical instability for the HAFS moving-nesting configuration (Suggested by GFDL collaborators and tested by HRD colleagues).
- Enable using upoff as an application/workflow-level config option.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
The upoff namelist option in FV3dycore has been added during a working session. Workflow level config option will need to be added.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #147: HAFS vortex initialization related code modernization
## Description
Provide a clear and concise description of the requested feature/capability.
Modernize the vortex initialization related source code with updated code standard.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Convert into f90+ coding standard and clean up and remove gotos as much as possible.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?
@JunghoonShin-NOAA and @ChuankaiWang-NOAA are currently working on this modernization.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #153: Enable using regional ESG grid for HAFS moving nesting
## Description
Explore and add the capability of using regional ESG grid for the HAFS moving nesting configuration.

## Proposed solution
- Generate collocated regional ESG grids with coarse and fine resolutions (e.g., with 6km and 2km grid spacings) covering the same regional parent domain.
- Subset and cut the fine-resolution 2-km regional parent ESG grid to generate the 2-km moving-nest domain.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #159: Update the time information column in hafs.trak.patcf
## Description
Provide a clear and concise description of the requested feature/capability.
The first column in hafs.trak.patcf corresponds to the output time in seconds relative to 00Z of each day. We would like to change it into seconds since model initialization time.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
Update the related source code to write out the needed time information in hafs.trak.patcf.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
Sync HAFS submodules and bring in HAFSv1a/a baseline configurations back to HAFS develop branch.
- Update HAFS submodules hafs_forecast.fd, hafs_gsi.fd, hafs_utils.fd, which were synced to their latest authoritative branches as of 11/13/2022. And hafs_post.fd is consistent with the version used by ufs-weather-model (hafs_forecast.fd).
- Bring in HAFSv1a/b baseline configurations back to HAFS develop branch.
- Enable generating regional ESG grid within HAFS application workflow (supporting both single domain and moving-nesting configurations) from (@BinLiu-NOAA and @BantwaleEnyew-NOAA).
- Modernize HAFS vortex initialization related source code (from @JunghoonShin-NOAA and @ChuankaiWang-NOAA)
- Update hafs_datool source code with MPI and OMP parallelization (from @yonghuiweng)
- Switch to use Intel 2022 compiler version on NOAA RDHPCS (Jet, Hera, Orion), switch to use Lua format modulefiles, remove application/workflow level support for wcoss_cray and wcoss_dell_p2 (from @BijuThomas-NOAA)
- Add upoff as a namelist option (from a working session among a few EMC/HRD colleagues).
- Fix the time information column in FV3 dycore internal tracker output partial atcf track file.
- Add the application/workflow capability of using orog_gsl and new UGWP scheme, which is not yet used in the HAFSv1a/b baseline configurations (from @XuLi-NOAA and @BinLiu-NOAA)

## Issues addressed
- fixes hafs-community/HAFS/issues/159
- fixes hafs-community/HAFS/issues/153
- fixes hafs-community/HAFS/issues/147
- fixes hafs-community/HAFS/issues/145
- partially addresses hafs-community/HAFS/issues/144
- fixes hafs-community/HAFS/issues/143
- fixes hafs-community/HAFS/issues/142
- fixes hafs-community/HAFS/issues/141

## Contributors
Lots of UFS HAFS application team members contributed to this PR. Details can be found in the Git commit log messages.

## Tests conducted
- Technical tests for HAFSv1a/b baseline configurations were conducted on multiple platforms by @yonghuiweng.
- HAFSv1a/b baseline experiments have been running on all four HAFS supported platforms (wcoss2, jet, hera, orion).
- HAFS application/workflow level regression tests succeeded on wcoss2.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS2

As usual, please help to conduct the HAFS application/workflow level regression tests for this PR.
@panll (Hera)
@mrinalbiswas (Orion)
@JunghoonShin-NOAA (Jet)
@BijuThomas-NOAA (wcoss2)

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@panll, @mrinalbiswas, @JunghoonShin-NOAA, @BijuThomas-NOAA, all the submodules are up to date now, please go ahead to start the application/workflow level regression tests when you get a chance. Thanks!

**Comment by BijuThomas-NOAA** [comment]
RT passed on WCOSS2

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by panll** [comment]
Regression tests passed on Hera except fails at Analysis (e.g. rt_regional_mvnest_vida) with error message /apps/lmod/8.5.2/libexec/lmod bash load gsi_hera.intel
Lmod has detected the following error: The following module(s) are unknown:
"mkl".
@BinLiu-NOAA

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin, Regression test is completed successfully on Jet.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
> Regression tests passed on Hera except fails at Analysis (e.g. rt_regional_mvnest_vida) with error message /apps/lmod/8.5.2/libexec/lmod bash load gsi_hera.intel Lmod has detected the following error: The following module(s) are unknown: "mkl". @BinLiu-NOAA

@panll, Thanks for testing! This is somewhat strange. A few of us are actually running the HAFSv1 baseline configurations on Hera (with DA turned on) and we did not encounter this gsi_hera.intel or mkl module load issue. @BijuThomas-NOAA or @lbi2018, could you please help to take a look at this. Thanks!

**Comment by yonghuiweng** [comment]
> @BinLiu-NOAA , I had the same issue on Jet. I added "module purge" into both JHAFS_ANALYSIS and JHAFS_ATM_POST to fix this issue.

**Comment by panll** [comment]
The "module purge" fixes the problem. Thanks! @BinLiu-NOAA @yonghuiweng

**Review by panll — APPROVED** [review]

**Review by mrinalbiswas — APPROVED** [review]
RTs passed on Orion

**Review by KathrynNewman — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks to @BijuThomas-NOAA, @JunghoonShin-NOAA, @panll and @mrinalbiswas for conducting the application level regression tests promptly for this PR! And @panll, for the gsi analysis job module purge issue on Hera, we will ignore it for now, since others did not have this issue. If it keeps coming next time, we will try to address this next time. Thanks!

**Pull request merged**
