### PR TITLE
HAFS application/workflow level script cleanups and point to ufs-weather-model develop branch

### LINKED ISSUE #169: Point to ufs-weather-model develop branch as of 12/13/2022
## Description
Update submodule hafs_forecast.fd to point to ufs-weather-model develop branch as of 12/13/2022.

## Proposed solution
Update submodule hafs_forecast.fd.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #170: Some HAFS application/workflow level script cleanups
## Description
Provide a clear and concise description of the requested feature/capability.
Script cleanups at the HAFS application/workflow level.
## Proposed solution
Go through HAFS scripts and try to make them closer to meet the [CODE_STYLE.md](https://github.com/hafs-community/HAFS/blob/develop/CODE_STYLE.md) requirements.

## Status (optional)
Happening in the feature/hafsv1_phase3 branch. A PR will be created soon.

## Related to (optional)
- fixed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
- Update submodule hafs_forecast.fd to point to the latest ufs-weather-model develop branch as of 12/13/2022.
- HAFS application/workflow level script cleanups.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/169
- fixes hafs-community/HAFS/issues/170

## Tests conducted
HAFS application/workflow level regression tests and HAFSv1a/b baseline technical tests passed on WCOSS2.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS2

Please help to conduct the HAFS application/workflow level regression tests for this PR.
@panll (Hera)
@mrinalbiswas (Orion)
@JunghoonShin-NOAA (Jet)
@BijuThomas-NOAA (wcoss2)

### CODE REVIEW

**Comment by BijuThomas-NOAA** [comment]
RT passed on WCOSS2

**Comment by panll** [comment]
RT tests passed on Hera with some minor fixes: 1) loading the module related to ndate for ic and lbc jobs and, 2) purging modules before loading modules for analysis.

**Review by panll — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
@panll, I made some module purge/load related changes in some jobs/JHAFS_* scripts. I was able to run the atm_ic/atm_lbc jobs on Hera from my end. Also, my analysis job worked as well. For @mrinalbiswas and @JunghoonShin-NOAA, if you got some module related issues for the regression tests on Orion/Jet, please git pull to get this set of changes. Thanks!

**Comment by JunghoonShin-NOAA** [comment]
Regression test on Jet is completed successfully, and atm_ic/LBC jobs worked properly even though I didn't use the updated jobs/JHAFS_* scripts.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks, @panll, @JunghoonShin-NOAA, @BijuThomas-NOAA! And @mrinalbiswas, I also tried running HAFS application/workflow level regression tests on Orion yesterday with the latest branch, and they all went through successfully. With that, I think this PR is ready to merge. Thanks!

**Pull request merged**
