### PR TITLE
HAFSv0.3 moving-nesting related coupling, vortex initialization, and data assimilation capabilities

### LINKED ISSUE #129: Merge HAFSv0.3 phase-2 configuration back to HAFS develop
## Description
The HAFSv0.3 phase2 configuration in the [feature/hafsv0.3_phase2](https://github.com/hafs-community/HAFS/tree/feature/hafsv0.3_phase2) branch contains the latest HAFS moving nesting, coupling, vortex initialization, data assimilation capabilities, and it points to the latest develop branch (as of 04/12/2022) of ufs-weather-model. Besides, the hafs_utils.fd and hafs_gsi.fd were also synced with their corresponding develop/master branches recently. With that, it would be beneficial to merge this feature branch back to HAFS develop branch.

## Proposed solution
Merge the feature/hafsv0.3_phase2 branch back to HAFS develop branch.

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- addressed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
The HAFSv0.3 phase2 configuration contains the latest HAFS moving nesting, coupling, vortex initialization, data assimilation capabilities, and it points to the latest develop branch (as of 04/12/2022) of ufs-weather-model. Besides, the hafs_utils.fd and hafs_gsi.fd were also synced with their corresponding develop/master branches recently. 

- Details and contributors regarding the hafs_forecast.fd level HAFS moving-nesting and coupling related developments can be seen from ufs-community/ufs-weather-model/pull/1104.
- The HWRF/HMON type vortex initialization (VI) capability mainly mainly developed/ported to HAFS by @Qingfu-Liu, @BinLiu-NOAA, @JunghoonShin-NOAA, @ChuankaiWang-NOAA.
- The HAFS datool developed by @yonghuiweng is used in HAFS VI pre- and post-processing procedures to interpolate FV3 restart files into the HAFS VI input data as well as HAFS VI analysis back to FV3 restart files. In addition, the HAFS datool is also used in atm_merge and analysis_merge jobs/tasks/steps for implementing various HAFS cold-start or warm-start cycling strategies.
- Implemented the HAFS VI/DA application/workflow capability for both regional single-domain and moving-nesting configurations.
- Added a HAFS application/workflow regression test in cronjob_hafs_rt.sh to test the regional storm-focused moving-nesting configuration with vortex initialization and domain 02 data assimilation.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/129

## Tests conducted
This feature/hafsv0.3_phase2 branch has been tested on various HAFS supported platforms.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS Dell P3
- [x] WCOSS Cray

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
Again, as you helped previously,  please help to conduct the HAFS application/workflow level regression tests for this PR.
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (Jet)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)

**Comment by BijuThomas-NOAA** [comment]
> Again, as you helped previously, please help to conduct the HAFS application/workflow level regression tests for this PR. @evankalina, @panll, @mrinalbiswas (Hera and Orion) @JunghoonShin-NOAA (Jet) @LinZhu-NOAA (wcoss_dell_p3) @BijuThomas-NOAA (wcoss_cray)

atm_vi,  atm_vi_fgat03, and  atm_vi_fgat06 of hafsv0.3_phase2_rt_regional_mvnest_vida failed for the second cycle on wcoss-cray.
The log file has several  NaN values.
@yonghuiweng: Can you take a look? Can you check if the interpolation in  hafs_datool is working properly?
/gpfs/hps3/ptmp/Biju.Thomas/hafsv0.3_phase2_rt_regional_mvnest_vida/2020082512/13L

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA The forecast job failed for the first cycle of da_C192s1n4_3denvar and regional_static_atm_ocn on wcoss-dell. The log file seems hang there.

**Comment by panll** [comment]
Regression tests passed on Hera after some minor modifications. @BinLiu-NOAA @evankalina  The post process numbers need to be increased (e.g., changing from 2 nodes to 4 nodes) to pass the tests on Hera for HAFS_rt_regional_atm_only, HAFS_rt_regional_static_atm_ocn, HAFS_rt_regional_atm_ocn_wav, HAFS_rt_regional_mvnest_vida, HAFS_rt_regional_static_atm_wav

**Comment by BinLiu-NOAA** [comment]
> Regression tests passed on Hera after some minor modifications. @BinLiu-NOAA @evankalina The post process numbers need to be increased (e.g., changing from 2 nodes to 4 nodes) to pass the tests on Hera for HAFS_rt_regional_atm_only, HAFS_rt_regional_static_atm_ocn, HAFS_rt_regional_atm_ocn_wav, HAFS_rt_regional_mvnest_vida, HAFS_rt_regional_static_atm_wav

Thanks, @panll! I am updating the ATM_POST_RESOURCES to use 4 nodes with 20 PEs per node as follows:
  <!ENTITY ATM_POST_RESOURCES "<nodes>4:ppn=20:tpp=1</nodes><envar><name>TOTAL_TASKS</name><value>80</value></envar><envar><name>NCTSK</name><value>20</value></envar><envar><name>OMP_THREADS</name><value>1</value></envar><walltime>07:59:00</walltime>">

Hopefully this will work fine.

**Comment by BijuThomas-NOAA** [comment]
> > Again, as you helped previously, please help to conduct the HAFS application/workflow level regression tests for this PR. @evankalina, @panll, @mrinalbiswas (Hera and Orion) @JunghoonShin-NOAA (Jet) @LinZhu-NOAA (wcoss_dell_p3) @BijuThomas-NOAA (wcoss_cray)
> 
> atm_vi, atm_vi_fgat03, and atm_vi_fgat06 of hafsv0.3_phase2_rt_regional_mvnest_vida failed for the second cycle on wcoss-cray. The log file has several NaN values. @yonghuiweng: Can you take a look? Can you check if the interpolation in hafs_datool is working properly? /gpfs/hps3/ptmp/Biju.Thomas/hafsv0.3_phase2_rt_regional_mvnest_vida/2020082512/13L

Regression tests passed on WCOSS(Cray) after using classic NetCDF option(-n4) for the mppnccombine executable.

**Review by BijuThomas-NOAA — APPROVED** [review]

**Review by panll — APPROVED** [review]

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
All regression tests for this branch passed successfully on Jet (Jet was slow again). No modification was needed to run all regression tests.
Thank you.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Review by mrinalbiswas — APPROVED** [review]
RTs passed on Orion.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA The forecast job failed for the first cycle of da_C192s1n4_3denvar and regional_static_atm_ocn on wcoss-dell. The log file seems hang there.

@LinZhu-NOAA, I have just pushed a fix for the forecast job hanging/failure on wcoss_dell_p3. Please "git pull" the latest changes and rewind the failed tasks. And they should now go through successfully. The issue was the inconsistent modules loaded in modulefile.hafs.wcoss_dell_p3. Thanks!

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA The regression tests completed successfully on WCOSS-Dell after updating the modules.

**Review by LinZhu-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks to @panll, @mrinalbiswas, @LinZhu-NOAA, @JunghoonShin-NOAA, @BijuThomas-NOAA for conducing the application level regression tests! And we have also fixed the hafsvi_pre-/postproc interpolation issues. So, I think this PR is ready merge now. Also, @evankalina, since this PR contains lots of developments and commits, I was thinking of merging this PR by keeping its commit log. Does is sound good to you? Thanks!

**Comment by evankalina** [comment]
@BinLiu-NOAA Keeping the list of commits sounds good to me. Congratulations on getting this PR ready!

**Review by evankalina — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks All! Merging to close this PR now.

**Pull request merged**
