### PR TITLE
Sync HAFS submodules as of 12/06/2021

### LINKED ISSUE #115: Switch to point ufs-weather-model develop branch directly
## Description
For the HAFS application/workflow develop branch, switch to point to the develop branch of the authoritative ufs-weather-model directly for the sorc/hafs_forecast.fd submodule.

## Proposed solution
Currently, the support/HAFS branch is identical to an early version (11/03/2021) of ufs-weather-model develop branch. When we plan our next round of update of the hafs_forecast.fd submodule inside HAFS, we can just directly point to the ufs-weather-model develop branch.

Note: The HAFS related developments will still be happening in the hafs-community fork of ufs-weather-model (e.g., the feature/hafs_nesting branch for the moving nesting development). 

## Related to (optional)
- associated with hafs-community/hafs/pull/<pr_number>

### LINKED ISSUE #116: Switch to point UPP develop branch directly
## Description
Currently, all HAFS related changes/developments for UPP have been merged back to UPP develop after this PR (NOAA-EMC/UPP/pull/418). So HAFS can switch to point UPP develop branch directly.

## Proposed solution
When we plan our next round of update of the hafs_post.fd submodule inside HAFS, we can just directly point to the UPP develop branch. Beside, UPP is also becoming a submodule of ufs-weather-model/FV3/upp (see NOAA-EMC/fv3atm/pull/421), so we can also consider to just symbolically link upp from sorc/hafs_forecast.fd/FV3/upp into sorc/hafs_post.fd.

## Related to (optional)
- addressed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description of changes
- Point submodule hafs_forecast.fd to ufs-weather-model develop branch directly (as of 12/06/2021)
- Point submodule hafs_post.fd to UPP develop branch directly (as of 12/06/2021)
- Sync hafs_utils.fd with latest UFS_UTILS develop branch as of 12/06/2021

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/115
- fixes hafs-community/HAFS/issues/116

## Tests conducted
What testing has been conducted on the PR thus far? Describe the nature of any scientific or technical tests, including relevant details about the configuration(s) (e.g., cold versus warm start, number of cycles, forecast length, whether data assimilation was performed, etc). What platform(s) were used for testing?

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS Dell P3
- [x] WCOSS Cray

Again, as you helped previously, let's conduct the HAFS application/workflow level regression tests for this PR.
@evankalina, @panll, @mrinalbiswas (Hera and Orion)
@JunghoonShin-NOAA (Jet)
@LinZhu-NOAA (wcoss_dell_p3)
@BijuThomas-NOAA (wcoss_cray)

### CODE REVIEW

**Comment by JunghoonShin-NOAA** [comment]
Hello Bin,
All regression tests of the hafs_sync_202112 branch were completed successfully on Jet. Especially, the wave (WW3) model part worked successfully at this time, which is very good news.
Thank you.

**Review by JunghoonShin-NOAA — APPROVED** [review]

**Comment by LinZhu-NOAA** [comment]
@BinLiu-NOAA The regression tests were completed successfully on WCOSS-DELL.

**Review by LinZhu-NOAA — APPROVED** [review]

**Comment by mrinalbiswas** [comment]
@BinLiu-NOAA RTs passed on Orion

**Comment by panll** [comment]
RTs passed on Hera (slightly delayed by maintenance). @BinLiu-NOAA @evankalina

**Review by panll — APPROVED** [review]

**Comment by BijuThomas-NOAA** [comment]
The RTs were successfully completed on WCOSS-CRAY

**Review by BijuThomas-NOAA — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks @JunghoonShin-NOAA, @LinZhu-NOAA, @mrinalbiswas, @panll and @BijuThomas-NOAA! Great that all HAFS application level regression tests went through smoothly on all five platforms. @evankalina, @KathrynNewman or @ZhanZhang-NOAA , please check and review this PR when you get a chance. Once it is approved, we can merge it into develop. Thanks!

**Review by evankalina — APPROVED** [review]
Good to go. Glad we can point directly to the ufs-weather-model and UPP repositories now.

**Pull request merged**
