### PR TITLE
Restore HAFS develop branch support for RDHPCS platforms after their recent OS system upgrades

### LINKED ISSUE #259: Enable/restore HAFS develop branch working on Jet/Hera/Orion with their OS system upgrades
## Description
Provide a clear and concise description of the requested feature/capability.
Hera and Jet are in the transition to Rocky8 OS. Need to enable HAFS working on Jet and Hera with the latest OS system upgrade.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/<pr_number>

### PR DESCRIPTION
**Pull request by BijuThomas-NOAA**
## Description of changes
Re-enable and restore HAFS develop branch with HAFSv1 configurations supporting all NOAA RDHPCS platforms with their recent OS system upgrades.

## Issues addressed (optional)
If this PR addresses one or more issues, please provide link(s) to the issue(s) here.
- fixes hafs-community/HAFS/issues/259

## Contributors (optional)
If others worked on this PR besides the author, please include their user names here (using @Mention if possible).

## Tests conducted
Technical testing has been done on multiple platforms.

## Application-level regression test status
Running the HAFS application-level regression tests is currently performed by code reviewers after the developer creates the initial PR. As regression tests are conducted, the testers should use the checklist below to indicate **successful** regression tests. You may add other tests as needed. If a test fails, do not check the box. Instead, describe the failure in the PR comments, noting the platform where the test failed.

- [x] Jet
- [x] Hera
- [x] Orion
- [x] WCOSS2

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
This PR is ready for HAFS application level regression testing. 
@LinZhu-NOAA, could you please take care of the RT on WCOSS2?
@BinLiu-NOAA, could you please run RT on Jet?
@BijuThomas-NOAA, could you please run RT on Hera?
@ChuankaiWang-NOAA could you please run RT on Orion?

Thanks!

P.S., here are the steps to clone, install, and run the HAFS RTs for this PR:
```
git clone -b feature/hafs.v1_202404 --recursive https://github.com/hafs-community/HAFS.git ./
cd sorc
nohup ./install_hafs.sh > install_hafs.log 2>&1 # This step will take a while, 30-min or longer
cd ../rocoto
export HOMEhafs=$(dirname $(pwd)) # or edit and update cronjob_hafs_rt.sh accordingly
./cronjob_hafs_rt.sh # repeatedly running or in crontab
```

**Comment by ChuankaiWang-NOAA** [comment]
The RT passed on Orion.

**Comment by LinZhu-NOAA** [comment]
The RT completed successfully on WCOSS2.

**Review by LinZhu-NOAA — APPROVED** [review]

**Review by ChuankaiWang-NOAA — APPROVED** [review]

**Comment by BijuThomas-NOAA** [comment]
passed on Hera

**Comment by BinLiu-NOAA** [comment]
Regression tests on Jet passed as well.

**Review by BinLiu-NOAA — APPROVED** [review]

**Pull request merged**
